### ISSUE TITLE
PubSub Implementation

### ISSUE THREAD

**Issue by zabawaba99** [alicebob/miniredis#1]
Do you have any intention on implementing the Pubsub portion of Redis?

**Comment by Al2Klimov** [comment]
Hello @alicebob and thank you for looking at this.

We – @Icinga – are developing a program that deals with a lot of Redis events and we'd like to get a unit test coverage near 100%.

Do I understand [you](https://github.com/alicebob/miniredis/issues/1#issuecomment-65455963) right that you can't implement this due to a problem with a dependency/framework/vendorlib of miniredis?

Best,
AK

**Comment by alicebob** [comment]
Hello Alexander,

this was true back in the days, but I've switched the server part to a custom implementation. I think it should be possible to implement now.
That said, I doubt I have time for this in the very near future.

**Comment by Al2Klimov** [comment]
Hello @alicebob and thank you for your quick reply!

Just got the permission to implement this myself. Should I take care about anything special like "don't do it like x, y or z as this have already been a problem in the past" or do you just give me green light for this?

Best,
AK

**Comment by alicebob** [comment]
I have not tried this, so I have no advise, so go for it.
Do have a look at the tests in ./integration/, and please add as many tests as needed there.

Have fun! Let me know if I can assist in any way. I'm happy to look at work-in-progress PRs if you need feedback.

**Comment by alicebob** [comment]
It sounds great if they are also directly executable, especially if they are published as Go channels.

I can image that it would come in handy when you make something which publishes a stream of notifications on redis, and you can read from a Go channel in the test to check what's going on. But, if you don't have any use-case for this yourself we can also add it later.

**Comment by Asalle** [comment]
Hey guys @Al2Klimov @alicebob!
how is the implementation of PUBLISH going? It would help me a lot.
Can I anyhow help to get it merged?

**Comment by Al2Klimov** [comment]
See #49.

**Comment by Asalle** [comment]
@Al2Klimov it seems that your fork is unmergeable to upstream and cannot be built 
```
# (I got the following error)
# github.com/Al2Klimov/miniredis
../../Al2Klimov/miniredis/direct.go:967:6: error: reference to undefined field or method ‘MsgQueue’
  peer.MsgQueue.Enqueue(&queuedPubSubMessage{channel, message})
      ^
../../Al2Klimov/miniredis/miniredis.go:169:3: error: reference to undefined field or method ‘OnDisconnect’
  s.OnDisconnect(m.onDisconnect)
```
Do you use your fork?

**Comment by Al2Klimov** [comment]
1. Both works for me.
2. We only use features merged into the master.

**Comment by Asalle** [comment]
Thanks for the hint! I used the feature branch.

**Comment by Asalle** [comment]
What do you mean by "master"? Al2Klimov/miniredis' master doesn't seem to contain any recent commits by you, all the pubsub stuff seems to be in `feature/pubsub-1` branch. Do you mean you use the upstream's master?

**Comment by alicebob** [comment]
Hi! Sorry, this PR dropped to the bottom of my todolist somehow. I'll try to have a good look soon, it's a long pr :)

**Comment by Al2Klimov** [comment]
Yes, the upstream master.
