### ISSUE TITLE
max/min filtering in ZREVRANGEBYSCORE broken

### ISSUE THREAD

**Issue by xh3b4sd** [alicebob/miniredis#10]
Hello there. I checked this project and found it cool. So I wanted to use it in one of my pet projects. There I had some tests that now fail when running against the miniredis implementation. For reference, when playing around with the `ZREVRANGEBYSCORE` command on http://redis.io/commands/zrevrangebyscore you can do things like this. We add an element with an specific score and fetch the element with this specific score in the max and min setting. Note that max is the first, and min the second score identifier.

Here the interface specification.
```
ZREVRANGEBYSCORE key max min [WITHSCORES] [LIMIT offset count]
```

Here the test on the website. 
```
redis> zadd key 3.3 element
(integer) 1
redis> zrevrangebyscore key 3.3 3.3
1) "element"
redis> zrevrangebyscore key 4.3 4.3
(empty list or set)
redis> 
```

Here the test using docker containers to make sure the redis website is not buggy. So run the redis server in one terminal.
```
docker run --rm --name redis -p 6379:6379 redis
1:C 09 Oct 21:43:55.441 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 3.2.3 (00000000/0) 64 bit
...
```

And run the redis-cli in another terminal.
```
docker run -it --rm --link redis:redis redis bash -c 'redis-cli -h redis'
redis:6379> zadd key 3.3 element
(integer) 1
redis:6379> zrevrangebyscore key 3.3 3.3
1) "element"
redis:6379> zrevrangebyscore key 4.3 4.3
(empty list or set)
redis:6379>
```

Here is the go program that fails with the same commands using miniredis.
```
package main

import (
	"fmt"

	"github.com/alicebob/miniredis"
	"github.com/garyburd/redigo/redis"
)

func main() {
	s, err := miniredis.Run()
	if err != nil {
		panic(err)
	}
	defer s.Close()

	c, err := redis.Dial("tcp", s.Addr())
	if err != nil {
		panic(err)
	}
	_, err = c.Do("ZADD", "key", 3.3, "element")
	if err != nil {
		panic(err)
	}
	res, err := redis.Strings(c.Do("ZREVRANGEBYSCORE", "key", 4.3, 4.3))
	if err != nil {
		panic(err)
	}
	fmt.Printf("%#v\n", res)
}
```

The result of the go program is `[]string{"element"}`, which is wrong, because there is no element in the set having score `4.3`. I checked the code but it is a little bit tricky for me to comprehend what is going wrong and where to fix this.

**Comment by xh3b4sd** [comment]
As I see it there is no code to filter elements according to their scores. There is only code to limit the returned number of elements, but this is something completely different. Further I think the implementation cannot work by design when there is one method that tries to manage `ZRANGEBYSCORE` and `ZREVRANGEBYSCORE`. Note that min/max are switched on these methods. 

```
ZRANGEBYSCORE    key min max [WITHSCORES] [LIMIT offset count]
ZREVRANGEBYSCORE key max min [WITHSCORES] [LIMIT offset count]
```

See http://redis.io/commands/zrangebyscore and http://redis.io/commands/zrevrangebyscore

**Comment by alicebob** [comment]
Thanks for your detailed bugreport! As far as I can see there was a problem when both min and max where bigger than the smallest score in the set. That's fixed now. Otherwise things seems to work well, also for ZREVRANGEBYSCORE when min and max are swapped.

**Comment by xh3b4sd** [comment]
Cool thing. Thanks for the support and fixing this. I will give it a try soon.

**Comment by xh3b4sd** [comment]
I checked back and it works for me. Thanks again.
