### ISSUE TITLE
Miniredis vs redis.io commands name mismatch

### ISSUE THREAD

**Issue by Asalle** [alicebob/miniredis#104]
Hey there,

is there a reason why some set(datastructure)-related commands in miniredis are called something different from the official redis command list? (https://redis.io/commands)
For example:
redis.io             minireids
SADD           -> SetAdd
SMEMBERS -> Members
whereas SREM and SRem are in sync.

As a result, it takes some time to figure out which command is which, at least for me.
Also, thank you for this amazing project! :heart:

**Comment by alicebob** [comment]
> Hey there,
> 
> is there a reason why some set(datastructure)-related commands in miniredis are called something different from the official redis command list? (https://redis.io/commands)
> For example:
> redis.io             minireids
> SADD           -> SetAdd
> SMEMBERS -> Members
> whereas SREM and SRem are in sync.
> 
> As a result, it takes some time to figure out which command is which, at least for me.

I think it's mostly for, euhm, "historical reasons" :)

Feel free to make a PR to introduce an alias for those functions! That would be
great.


> Also, thank you for this amazing project! :heart: 

Thanks!

**Comment by Asalle** [comment]
you mean something like this?
```
// LPop is an alias for Pop
func (m *Miniredis) LPop(k string) (string, error) {
	return m.Pop(k)
}
// Pop removes and returns the last element. Is called RPOP in Redis.
func (m *Miniredis) Pop(k string) (string, error) {
	return m.DB(m.selectedDB).Pop(k)
}
```

**Comment by alicebob** [comment]
On Mon, Sep 09, 2019 at 02:00:36PM -0700, Asal Mirzaieva wrote:
> you mean something like this?

Yes. Execpt that that should be `Rpop`, not `Lpop`?

**Comment by Asalle** [comment]
The only thing is, I don't know how to test it. I mean it's just a couple of aliases for existing funcitons and docs, so ?
