### ISSUE TITLE
[feature] UNLINK command not supported

### ISSUE THREAD

**Issue by Asalle** [alicebob/miniredis#106]
Hey there,

since redis 4.0.0 the project supports `UNLINK` (which is basically async `DEL`), detailed decription [here](https://redis.io/commands/unlink). 

Do you think it's going to be possible to add this command? How can I help?

Asa

**Comment by alicebob** [comment]
> Hey there,

hi, thanks for the issue!

> since redis 4.0.0 the project supports `UNLINK` (which is basically async `DEL`), detailed decription [here](https://redis.io/commands/unlink). 
> 
> Do you think it's going to be possible to add this command?

Seems easy enough, and we might get away with implementing it as an alias for
DEL?

> How can I help?

Open a PR implementing it :)
Otherwise I'll add it when I get around to it, should be easy.

**Comment by Asalle** [comment]
Yes, for unit testing I guess it does not matter if it's async or not and the performance should be tested against a real redis, so the alias should suffice, nice hack :)
I'll try to come back with a pr on the weekend.
Thank you for the quick reply and for maintaining this cool incredible project! :rocket:
