### ISSUE TITLE
Go mod cannot get release v2.10.0

### ISSUE THREAD

**Issue by weihesdlegend** [alicebob/miniredis#109]
I am using go 1.13 and go mod. Currently in `go.mod` the version stays in the version below. 
`github.com/alicebob/miniredis v2.5.0+incompatible`

When I tried to force it to use v2.10.0 by `go mod edit -require github.com/alicebob/miniredis@v2.10.0`. It says `require github.com/alicebob/miniredis: version "v2.10.0" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2`

**Comment by alicebob** [comment]
Thanks for your question, @weihesdlegend!

You'll have to import the v2 version:

```
package main

import (
    "github.com/alicebob/miniredis/v2"
)

func main() {
    miniredis.Run()
}
```

That way you'll get v2.10.1, which is the latest.

Let me know if that doesn't help, or isn't your question.

**Comment by weihesdlegend** [comment]
Hi @alicebob, thank you so much! I tried your method and it worked! 
Thanks for unblocking us and this neat trick! Sometimes we are constraint when using go.mod.

**Comment by alicebob** [comment]
> Hi @alicebob, thank you so much! I tried your method and it worked! 
> Thanks for unblocking us and this neat trick! Sometimes we are constraint when using go.mod. 

Great, happy it works now!
