### ISSUE TITLE
ERR unknown command 'brpop'

### ISSUE THREAD

**Issue by xh3b4sd** [alicebob/miniredis#11]
This issue is rather a question. I see commands like `brpop` are not implemented. Can we have a discussion about this? Why are such commands not implemented? One of my pet projects makes use of `brpop`. Now I added miniredis to test my storage implementations. It would be supreme to have support for these commands. Cheers.

**Comment by alicebob** [comment]
Originally they were not implementd because I don't use them, but I think these could be done.

Commands which return multiple replies for a single command (MONITOR, the PUBSUB related commands) won't work because of the library we use to implement the server. Which commands do you use exactly?

**Comment by xh3b4sd** [comment]
I have some very simple queue implementation based on redis. Publishers write elements into some queue using this command.

```
LPUSH key element
```

`LPUSH` works fine. What is missing now is the companion. In my case consumers read elements from some queue using this command. 

```
BRPOP key
```

The only "tricky" part here is that the redis implementation of `BRPOP` specifies to block until there is one element. It is also that you can specify multiple keys and an timeout. See http://redis.io/commands/brpop. 

So there are multiple features `BRPOP` provides. Theoretically these could be provided by miniredis step by step. In my current case for instance I am not using multiple keys or timeouts.

**Comment by alicebob** [comment]
OK, it should be doable, but it requires some bigger changes. I plan to have a look when I have a few spare hours.

**Comment by xh3b4sd** [comment]
Hey that sounds good man. Let me know when you need a hand.

**Comment by alicebob** [comment]
BRPOP should be in master. Do let me know how it behaves for you. If it seems to work I'll make BLPOP and BRPOPLPUSH.

**Comment by xh3b4sd** [comment]
Cool pal. Thanks in advance. Will come back to you as soon as I have checked on that one.

**Comment by xh3b4sd** [comment]
So far as I can see it works for me. Thanks again. :)
