### ISSUE TITLE
[bug] LUA Eval is executing scripts in parallel. creates race condition absent in redis.

### ISSUE THREAD

**Issue by jwmay2012** [alicebob/miniredis#111]
Redis executes LUA scripts in a transactional manor in a shard. (when the KEYS hash slots are in the same shard)
miniredis seems to be executing LUA scripts outside of a lock which caused some unreliable tests for me. I have a bit of LUA that depends on the transactional nature of it's execution. 

This fixes the issue:
Adding `scriptLock sync.Mutex` to `miniredis.go`

```
// Miniredis is a Redis server implementation.
type Miniredis struct {
	sync.Mutex
	srv        *server.Server
	port       int
	password   string
	dbs        map[int]*RedisDB
	selectedDB int               // DB id used in the direct Get(), Set() &c.
	scripts    map[string]string // sha1 -> lua src
	signal     *sync.Cond
	now        time.Time // used to make a duration from EXPIREAT. time.Now() if not set.
	
	scriptLock sync.Mutex
}
```

And locking LUA execution in `cmd_scripting.go:25` `runLuaScript` 

```
// Execute lua. Needs to run m.Lock()ed, from within withTx().
func (m *Miniredis) runLuaScript(c *server.Peer, script string, args []string) {

	// ...
	l.Push(lua.LString("redis"))
	l.Call(1, 0)

	m.Unlock() // This runs in a transaction, but can access our db recursively
	defer m.Lock()
	
	// **********  NEW LUA LOCK  **************
	m.scriptLock.Lock()
	defer m.scriptLock.Unlock()

	if err := l.DoString(script); err != nil {
		c.WriteError(errLuaParseError(err))
		return
	}

	luaToRedis(l, c, l.Get(1))
}
```

I wont pretend that this solution is clean enough to be 'the' solution, but its working for me so far and showcases the issue for someone with more experience in the miniredis codebase to make a sufficiently elegant solution. 

If you want, I could provide a test case for the issue (and a PR with my current solution, if you want it).

I'm finding miniredis vitally useful for testing my project.
My thanks to the creators and maintainers of this project! 
:)

Let me know if I can assist in resolving this issue further.

**Comment by alicebob** [comment]
Hi Jordan,

thanks for the detailed explanation! A PR with a test and your solution would
be great, if you have one anyway. Ideally as two different commits: one with
the test, and one with the new lock.

**Comment by alicebob** [comment]
Should be fixed in master. Thanks for the report!
