### ISSUE TITLE
TCP timeout when executing Select() in TxPipeline

### ISSUE THREAD

**Issue by zypox** [alicebob/miniredis#114]
I'm getting read TCP timeout error when executing `Select(db)` method on `TxPipeline()` instance. The issue occurs when I'm using miniredis with go-redis client. Example code:

```
	mr, err := miniredis.Run()
	if err != nil {
		panic(err)
	}
	defer mr.Close()

	redisClient := redis.NewClient(&redis.Options{
		Addr: mr.Addr(),
		DB:   1,
	})

	redisClient.Incr("someKey")

	pipe := redisClient.TxPipeline()
	pipe.Select(1)
	pipe.Get("someKey")

	if _, err := pipe.Exec(); err != nil {
		fmt.Println(err)
	}
```

Output:

```
read tcp 127.0.0.1:52258->127.0.0.1:52257: i/o timeout
```

The strange part is that when I'm executing `Get()` on non-existing key, I'm not getting this error, it simply returns `nil` in that case (as expected). Also, the code works as expected when I'm using `Pipeline()` instead of `TxPipeline()`.

**Comment by alicebob** [comment]
> I'm getting read TCP timeout error when executing `Select(db)` method on `TxPipeline()` instance.

Thanks for the bugreport! Sounds like some nice locking problem. I'll have a
look soon.

**Comment by alicebob** [comment]
Sorry for the delay! Should be fixed in master.
