### ISSUE TITLE
Lua Eval fails to process integers that are larger than 6 digits when used with redis.call

### ISSUE THREAD

**Issue by jenyad20** [alicebob/miniredis#117]
redis.call('expire', myKey, 1000000) will cause an error, "ERR Error compiling script (new function): <string>:31: ERR value is not an integer or out of range"
redis.call('expire', myKey, 999999) will work without an issue
Reproduced in version 2.7.0
Edit:
The bug does not reproduce when working with a real redis server, so its only a mock server issue.
found a workaround, redis.call('expire', myKey, '1000000'), using a string instead of integer will work.

**Comment by alicebob** [comment]
> redis.call('expire', myKey, 1000000) will cause an error, "ERR Error compiling script (new function): <string>:31: ERR value is not an integer or out of range"
> redis.call('expire', myKey, 999999) will work without an issue

Curious. Thanks for the report!, I'll have a look soon.

**Comment by alicebob** [comment]
Sorry for the delay, should be fixed in master.
