### ISSUE TITLE
Stream XREAD support

### ISSUE THREAD

**Issue by wenweih** [alicebob/miniredis#118]
Hi, thanks for maintainers.

is whether Stream support `XREAD` operations?

According the syntax, it seem not support yet.
```
// commandsStream handles all stream operations.
func commandsStream(m *Miniredis) {
	m.srv.Register("XADD", m.cmdXadd)
	m.srv.Register("XLEN", m.cmdXlen)
	m.srv.Register("XRANGE", m.makeCmdXrange(false))
	m.srv.Register("XREVRANGE", m.makeCmdXrange(true))
}
```

**Comment by alicebob** [comment]
> is whether Stream support `XREAD` operations?

Hi,

the stream operations are very new, and there is no XREAD. It will be quite a
bit of work to add :(

**Comment by wenweih** [comment]
@alicebob Got it, thanks.
