### ISSUE TITLE
HSET doesn't support multiple field/value pairs

### ISSUE THREAD

**Issue by carlgreen** [alicebob/miniredis#120]
Hi,

As per https://redis.io/commands/hset HSET now allows multiple field/value pairs, which unfortunately miniredis does not.

cmdHset() in cmd_hash.go has a hard-coded check that args array contains three items (key, field, and value) and hashSet() in db.go would need to be a variadic function. I'm happy to have a go at implementing this if that would help.

**Comment by alicebob** [comment]
On Thu, Nov 28, 2019 at 02:25:08PM -0800, carl wrote:
> Hi,
> 
> As per https://redis.io/commands/hset HSET now allows multiple field/value pairs, which unfortunately miniredis does not.
> 
> cmdHset() in cmd_hash.go has a hard-coded check that args array contains three items (key, field, and value) and hashSet() in db.go would need to be a variadic function. I'm happy to have a go at implementing this if that would help.

That would be great! Also please add some tests to the ./integration/ subdir.

Otherwise I'll add support for this later, it shouldn't be too much work.
