### ISSUE TITLE
Contribute with GEORADIUSBYMEMBER

### ISSUE THREAD

**Issue by kyeett** [alicebob/miniredis#130]
Hi!

First of all, thank you for a great package!

I would like GEORADIUSBYMEMBER for a hobby project.  Can I try to implement it and create a PR for it? 

Best regards,
Magnus

**Comment by alicebob** [comment]
> First of all, thank you for a great package!

Thanks!

> I would like GEORADIUSBYMEMBER for a hobby project.  Can I try to implement it and create a PR for it? 

Absolutely! Would be great!

**Comment by kyeett** [comment]
Created #131. Please have a look

**Comment by alicebob** [comment]
Merged, thanks!
