### ISSUE TITLE
FYI: Error message changed in redis between 5.0.3 and 5.0.7

### ISSUE THREAD

**Issue by cleroux** [alicebob/miniredis#136]
stream_test.go:10: error error. expected: "ERR The ID specified in XADD must be greater than 0-0" got: "ERR The ID specified in XADD is equal or smaller than the target stream top item" case: main.command{cmd:"XADD", args:[]interface {}{"newplanets", "0", "foo", "bar"}, error:true, sort:false, loosely:false, errorSub:"", receiveOnly:false, roundFloats:0, closeChan:false, noResultCheck:false}

**Comment by cleroux** [comment]
Please feel free to close this issue.  Just wanted to let you know about this change if you ever update your library.

**Comment by alicebob** [comment]
On Sun, Feb 16, 2020 at 02:06:11PM -0800, cleroux wrote:
> stream_test.go:10: error error. expected: "ERR The ID specified in XADD must be greater than 0-0" got: "ERR The ID specified in XADD is equal or smaller than the target stream top item" case: main.command{cmd:"XADD", args:[]interface {}{"newplanets", "0", "foo", "bar"}, error:true, sort:false, loosely:false, errorSub:"", receiveOnly:false, roundFloats:0, closeChan:false, noResultCheck:false}

Thanks! I'll update it in a few days.

**Comment by alicebob** [comment]
Thanks! Fixed in master now. I'll have a proper look at the other issue another day.
