### ISSUE TITLE
ZUNIONSTORE does not support standard set types

### ISSUE THREAD

**Issue by wshirey** [alicebob/miniredis#140]
Redis docs do not explicitly detail this, but it is possible to use ZUNIONSTORE on standard sets. For example

```
sadd super 1 2 3
sadd exclude 3
zunionstore tmp 2 super exclude weights 1 0 aggregate min
zrange tmp 0 -1 withscores
```

will result in
```
"3"
"0"
"1"
"1"
"2"
"1"
```

Currently only sorted sets are being allowed and throwing a `WRONGTYPE` error here:
https://github.com/alicebob/miniredis/blob/master/cmd_sorted_set.go#L609

**Comment by alicebob** [comment]
On Mon, Mar 02, 2020 at 06:13:42AM -0800, Wally S wrote:
> Redis docs do not explicitly detail this, but it is possible to use ZUNIONSTORE on standard sets. For example

Thanks for the issue, I'll have a look!

**Comment by alicebob** [comment]
Thanks! Released as https://github.com/alicebob/miniredis/releases/tag/v2.11.4
