### ISSUE TITLE
TOUCH implementation is incorrect

### ISSUE THREAD

**Issue by cleroux** [alicebob/miniredis#142]
I've just learned, rather embarassingly, that TOUCH does not work the way I thought it did.

Please see this ticket for some details: https://github.com/antirez/redis/issues/5719

In fact the implementation that I submitted in #135 is incorrect.  I have not yet had a chance to fully investigate how this would work in miniredis, but it's possible that TOUCH may actually just be a dummy non-operation in miniredis.

I would be happy to spend some time on this during the weekend if you like.  I just wanted to inform you of this as soon as possible.  I'm very sorry for the confusion.

**Comment by alicebob** [comment]
> I would be happy to spend some time on this during the weekend if you like.  I just wanted to inform you of this as soon as possible.  I'm very sorry for the confusion.

Thanks for getting back!
Looks like TOUCH should indeed be a simple NOOP. I don't have time for a proper
look right now, but will in a few days. Unless you're quicker than me.
