### ISSUE TITLE
PERSIST does not work in Lua script

### ISSUE THREAD

**Issue by jtyers** [alicebob/miniredis#144]
First off, thank you for writing this excellent library. Makes it so much easier to test Lua scripts in Redis!

I have a script that calls `PERSIST`, like so:

```
  -- some other code..
  redis.call('persist', KEYS[2]) -- otherwise not always persistent
```

The key is set up in my test to have a 10s expiry beforehand (via `SetTTL()`). However when I check the expiry of the key with `TTL(key)` after this script has run, the TTL is not reset to zero as I would expect.

I'm aware `FastForward()` is needed when wanting keys to expire, but this is the other way round. I would expect `PERSIST` to simply clear the expiry for the key, as I believe it does in real Redis.

Is this a bug, or am I missing something?

**Comment by alicebob** [comment]
> Is this a bug, or am I missing something?

Thanks for the issue! I'll have a look soon.

**Comment by jtyers** [comment]
Just to confirm the above, here's a mini-test case that proves the behaviour:

```
import (
	"testing"
	"time"
	"github.com/alicebob/miniredis/v2"
	"github.com/go-redis/redis"
	"github.com/stretchr/testify/require"
)

func TestMiniredisPersist(t *testing.T) {
	redisServer, err := miniredis.Run()
	defer redisServer.Close()

	client := redis.NewClient(&redis.Options{
		Addr: redisServer.Addr(), // use default Addr
	})

	key := "my-key"
	client.Set(key, "some-value", 1*time.Second)

	s := redis.NewScript(`
		-- simply persist the first key passed
		redis.call('persist', KEYS[1])
	`)

	_, err = s.Run(client, []string{key}).Result()
	require.Equal(t, err, redis.Nil)

	ttl, err := client.TTL(key).Result()
	require.Nil(t, err)
	require.Equal(t, 0, ttl)
}
```

Result:
```
--- FAIL: TestMiniredisPersist (0.00s)
    dataloader_test.go:444: 
        	Error Trace:	dataloader_test.go:444
        	Error:      	Not equal: 
        	           	expected: int(0)
        	           	actual  : time.Duration(-1000000000)
        	Test:       	TestMiniredisPersist
```

**Comment by alicebob** [comment]
Hah, that was fun. `TTL` returns `-1` if there is no TTL set. See the example at https://redis.io/commands/persist :

```
redis>  SET mykey "Hello"
"OK"
redis>  EXPIRE mykey 10
(integer) 1
redis>  TTL mykey
(integer) 10
redis>  PERSIST mykey
(integer) 1
redis>  TTL mykey
(integer) -1
redis> 
```
That explains it?

**Comment by jtyers** [comment]
Ah, that is a bug in my test! `miniredis.TTL()` returns zero if no expiry is set, which will be what threw me.

I'll investigate further.  The original code I saw the failure in was reporting the original expiry (`10s`). Some more testing I've done with miniredis suggests the bug is in my code.

Sorry! Closing.

**Comment by alicebob** [comment]
`miniredis.TTL()` returns zero if no expiry is set

That's indeed a bit weird, but nothing I can change at this stage of the
library :(

> Sorry! Closing.

Thanks! Good luck with testing, and do open issues for any other problems or
wishes.
