### ISSUE TITLE
MIssing package error: /home/sanket/.glide/cache/src/https-github.com-alicebob-miniredis/v2

### ISSUE THREAD

**Issue by continuum-sanket-khote** [alicebob/miniredis#145]
Error scanning github.com/alicebob/miniredis/v2: cannot find package "." in:
        /home/sanket/.glide/cache/src/https-github.com-alicebob-miniredis/v2
[ERROR] Failed to retrieve a list of test dependencies: Error resolving imports

I've used this import
"github.com/alicebob/miniredis/v2"

but still its not working

Go version 1.14

**Comment by alicebob** [comment]
Hi,
thanks for opening an issue.

I'm not familiar with Glide, but might it be that it doesn't have Go modules enabled? I messed up the transition to modules, so you need them now. See also #78.
If Go modules are enabled I don't know what's going wrong.
