### ISSUE TITLE
"setex" executes ok but key not expired

### ISSUE THREAD

**Issue by little-pan** [alicebob/miniredis#149]
```shell
>setex a 1 10
OK
.... after 1s
>get a
"10"
```

**Comment by alicebob** [comment]
Hi @little-pan . Thanks for your issue.

You'll need to call m.FastForward(1 * time.Second) for TTLs to work. See also https://github.com/alicebob/miniredis#ttls-key-expiration-and-time

**Comment by little-pan** [comment]
Why not expired automatically in miniredis?

**Comment by alicebob** [comment]
> Why not expired automatically in miniredis?

Because it's easier to test the values if they don't change. And you can "fast
forward" time as much as you want, without having to use `time.Sleep(...)`.
