### ISSUE TITLE
Miniredis sometimes hangs if connection is unused

### ISSUE THREAD

**Issue by aberkan** [alicebob/miniredis#151]
I've got a simple example program that hangs about 1 in 20 times I run it.  If I uncomment the line that uses the connection then it never hangs.  If I comment the connection Close it still occasionally hangs.  If I comment out the connection completely it works fine.

This is impacting some tests I'm writing where sometimes the test ends while a connection has been created but not used.
[foo.go.gz](https://github.com/alicebob/miniredis/files/4653086/foo.go.gz)

**Comment by alicebob** [comment]
Thanks for the clear bug report!

There was a problem shutting down the server _right_ after a new connection was made. A small `time.Sleep(time.Millisecond)` also worked as a workaround.

Could you check if the `quick` branch (#153) fixes it for you?

**Comment by aberkan** [comment]
Thanks for the quick fix.  It's working great!

**Comment by alicebob** [comment]
Thanks. It's merged in master, I'll make a new release in a few days.

**Comment by aberkan** [comment]
Hey,

Thanks for fixing this in master.  Have you had a chance to do a new
release?

Thanks,
Adam

**Comment by alicebob** [comment]
> Thanks for fixing this in master.  Have you had a chance to do a new
> release?

Thanks for the reminder!, I forgot about that.
https://github.com/alicebob/miniredis/releases/tag/v2.12.0
