### ISSUE TITLE
Tls support

### ISSUE THREAD

**Issue by caitong93** [alicebob/miniredis#155]
Hi, thanks for the awesome project ! 

It would be great if we can setup a  [tls](https://redis.io/topics/encryption) redis server. Is there any plan to support it ?

**Comment by alicebob** [comment]
Hi,

That seems possible, since Go has good support for TLS. I'll give it a try in a few days, but of course a PR is always welcome :)

**Comment by caitong93** [comment]
Thank you for the quick response.  I'm glad to take this, feel free to assign to me  : )

**Comment by alicebob** [comment]
#159 adds TLS versions. It leaves creating the `*tls.Config` to the caller, though.

**Comment by caitong93** [comment]
> #159 adds TLS versions. It leaves creating the *tls.Config to the caller, though.

I think this is fine, user can make custom configuration.

**Comment by alicebob** [comment]
I merged it, and made a release: https://github.com/alicebob/miniredis/releases/tag/v2.13.0

If anyone wants to make some helpers to make the certificate stuff easier, that would be great.
