### ISSUE TITLE
Unable to test pub/sub with go-redis

### ISSUE THREAD

**Issue by AnhTaFP** [alicebob/miniredis#157]
Hi, I'm having trouble running a couple of tests with [go-redis](https://github.com/go-redis/redis) and `miniredis`
I'm using go-redis version `6.15.2`, and miniredis version `2.5.0`

My test code looks something like this
```
	miniR, err := miniredis.Run()
	if err != nil {
		log.Fatal(err)
	}

	c := redis.NewClient(&redis.Options{
		Addr:     miniR.Addr(),
	})

	pubsub := c.Subscribe("mychannel")
	msg, err := pubsub.Receive()
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(msg)
```

The error I received is
```
2020/06/10 16:02:19 ERR unknown command `subscribe`, with args beginning with: `mychannel`, 
```

I tested my code against a redis docker container, and it works fine, so maybe it's miniredis' problem. Can you help me figure out why this happens, and how to fix it? Thanks a lot!

**Comment by alicebob** [comment]
On Wed, Jun 10, 2020 at 01:04:47AM -0700, Viet Anh wrote:
> I tested my code against a redis docker container, and it works fine, so maybe it's miniredis' problem. Can you help me figure out why this happens, and how to fix it? Thanks a lot!

Thank you for your bug report, I will have a look soon.

**Comment by alicebob** [comment]
You need to import miniredis v2:

```
package main

import (
    "fmt"

    "github.com/alicebob/miniredis/v2"
    "github.com/go-redis/redis"
)

func main() {
    miniR, err := miniredis.Run()
    if err != nil {
        panic(err)
    }

    c := redis.NewClient(&redis.Options{
        Addr: miniR.Addr(),
    })

    pubsub := c.Subscribe("mychannel")
    msg, err := pubsub.Receive()
    if err != nil {
        panic(err)
    }

    fmt.Println(msg)
}
```

It works that way?

**Comment by AnhTaFP** [comment]
Thanks, I imported v2 and it worked as expected
