### ISSUE TITLE
"SET key PX" does not work

### ISSUE THREAD

**Issue by etaic** [alicebob/miniredis#160]
see code, when use "PX" param, the expire time is not processed.
![image](https://user-images.githubusercontent.com/49184802/84990218-67dd4380-b177-11ea-9e86-063b851e79d8.png)

**Comment by alicebob** [comment]
Hi,
thanks for your issue!

The `PX` case you highlighted has a `fallthrough`, so it continues with the `EX` case below it. There the `ttl` is set, at line https://github.com/alicebob/miniredis/blob/master/cmd_string.go#L88.

Can you maybe give a test which shows it doesn't work?

**Comment by etaic** [comment]
I'm sorry, you are true, ttl is set when use **PX** param, but use **GET** cmd  there is no filter key that is set **ttl** .

eg:
```
package main

import (
	"fmt"
	"time"

	"github.com/alicebob/miniredis"
	"github.com/gomodule/redigo/redis"
)

func main() {
	s, err := miniredis.Run()
	if err != nil {
		panic(err)
	}
	defer s.Close()
	c, err := redis.Dial("tcp", s.Addr())
	var (
		key, value, expire = "test", "1", 50
	)
	_, err = c.Do("SET", key, value, "PX", expire)
	if err != nil {
		panic(err)
	}
	fmt.Println("ttl: ", s.TTL(key))
	time.Sleep(300 * time.Millisecond)
	result, err := redis.String(c.Do("GET", key))
	if err != nil {
		panic(err)
	}
	fmt.Println("result: ", result)
}
```

output:
```
ttl:  50ms
result:  1
```
https://github.com/alicebob/miniredis/blob/master/cmd_string.go#L341.

**Comment by alicebob** [comment]
Thanks for your explanation. Miniredis behaves as if time is frozen.
Instead of
`time.Sleep(300 * time.Millisecond)`
you need to do:
`s.FastForward(300 * time.Millisecond)`.

This makes it possible to test all the TTL values, and to avoid using Sleep()s.

**Comment by etaic** [comment]
thanks, my problem is solved~

**Comment by symbolss** [comment]
if i dont need this feature and i must use time.Sleep to simulate my case,what can i do?

> Thanks for your explanation. Miniredis behaves as if time is frozen. Instead of `time.Sleep(300 * time.Millisecond)` you need to do: `s.FastForward(300 * time.Millisecond)`. This makes it possible to test all the TTL values, and to avoid using Sleep()s.

**Comment by alicebob** [comment]
On Thu, Jun 10, 2021 at 07:55:50AM -0700, Symbol wrote:
> if i dont need this feature and i must use time.Sleep to simulate my case,what can i do?

Something along the lines of:

time.Sleep(1 * time.Second)
s.FastForward(1 * time.Second)

?

**Comment by symbolss** [comment]
> On Thu, Jun 10, 2021 at 07:55:50AM -0700, Symbol wrote: if i dont need this feature and i must use time.Sleep to simulate my case,what can i do?
> Something along the lines of: time.Sleep(1 * time.Second) s.FastForward(1 * time.Second) ?

i have a lib lock function:
func (r *ctxRedis) TryLock(key string, acquireTimeout, expireTimeout time.Duration) (uuid string, err error) {
	deadline := time.Now().Add(acquireTimeout)
	for {
		if time.Now().After(deadline) {
			return "", errors.New("lock timeout")
		}
		uuid, err = r.Lock(key, expireTimeout)
		if err != nil {
			time.Sleep(time.Millisecond)
		} else {
			return uuid, err
		}
	}
}
i need to test the **caller**,i can't modify this TryLock function

**Comment by symbolss** [comment]
i read the code,we did not call checkTTL in any get* cmd,so ttl is not work as real redis,if we can provide a option to call checkTTL in all get* cmd?

**Comment by alicebob** [comment]
> i read the code,we did not call checkTTL in any get* cmd,so ttl is not work as real redis,if we can provide a option to call checkTTL in all get* cmd?

checkTTL is called in the FastForward() function. You can call that before you
start the TryLock() test. Or if you want to have the delay in the test, you can
do a sleep and then FastForward() in a go routine.
