### ISSUE TITLE
Feature request: Username support in auth command

### ISSUE THREAD

**Issue by cdelacruzpinto** [alicebob/miniredis#161]
Redis 6 introduces ACL support. For that, they added a new username parameter, which is still not supported apparently in miniredis.

This can be seen here: https://redis.io/topics/acl

"The Redis AUTH command was extended in Redis 6, so now it is possible to use it in the two-arguments form:

AUTH <username> <password>"

**Comment by alicebob** [comment]
> This can be seen here: https://redis.io/topics/acl
> 
> "The Redis AUTH command was extended in Redis 6, so now it is possible to use it in the two-arguments form:
> 
> AUTH <username> <password>"

Good point!, I'll have a look soon.

(or if anyone feels like making a PR, also fine :)

**Comment by alicebob** [comment]
I merged #162 to master, I'll make it a new release in a week or so.

**Comment by cdelacruzpinto** [comment]
That is really cool. It allows making more accurate tests. Thanks for your work and your time :-)
