### ISSUE TITLE
Poor Performance with Failed Transaction Inside Watch

### ISSUE THREAD

**Issue by enjmusic** [alicebob/miniredis#163]
I've been writing some tests for a service that takes a separate action when a watch fails due to concurrent modification, and am running into a performance issue when trying to write a test that exercises this, using `go-redis` v8 and `miniredis`. The smallest repro I have is shown here:

```Go
package main

import (
	"context"
	"testing"

	"github.com/alicebob/miniredis"
	"github.com/go-redis/redis/v8"
)

func TestRepro(t *testing.T) {
	mini, err := miniredis.Run()

	if err != nil {
		t.Logf("Error creating miniredis server: %s", err)
		t.Fail()
	}

	defer mini.Close()

	client1 := redis.NewClient(&redis.Options{
		Addr:     mini.Addr(),
		Password: "",
		DB:       0,
	})

	client2 := redis.NewClient(&redis.Options{
		Addr:     mini.Addr(),
		Password: "",
		DB:       0,
	})

	defer client1.Close()
	defer client2.Close()

	ctx := context.Background()
	watchErr := client1.Watch(ctx, func(tx *redis.Tx) error {
		// Set key from other client to make transaction below fail
		client2.Set(ctx, "foo", "bar", 0)

		_, err := tx.TxPipelined(ctx, func(pipe redis.Pipeliner) error {
			pipe.Set(ctx, "foo", "baz", 0)
			return nil
		})
		return err
	}, "foo")

	if watchErr == nil {
		t.Log("No error in watch, expected error")
		t.Fail()
	}
}
```

Consistently, the `TxPipelined` inside the watch takes 3 seconds to run. Is it possible to improve the performance of this case? When running tests in our CI with `-count=4 -timeout=10000ms` this ends up timing out due to how long the transaction takes.

**Comment by alicebob** [comment]
On Wed, Jun 24, 2020 at 10:48:50AM -0700, Ian Hoffman wrote:
> I've been writing some tests for a service that takes a separate action when a watch fails due to concurrent modification, and am running into a performance issue when trying to write a test that exercises this, using `go-redis` v8 and `miniredis`. The smallest repro I have is shown here:

Thanks for the issue and the test, that'll help. I'll have a look soon-ish.

(btw, you should import "github.com/alicebob/miniredis/v2", but it likely won't
matter for this problem)

**Comment by enjmusic** [comment]
Using `github.com/alicebob/miniredis/v2` actually seems to have improved performance substantially, from 3 seconds to around 0.75 seconds!

**Comment by alicebob** [comment]
Here the test runs in basically no time:
```
$ go test -count=4 -v
=== RUN   TestRepro
--- PASS: TestRepro (0.00s)
=== RUN   TestRepro
--- PASS: TestRepro (0.00s)
=== RUN   TestRepro
--- PASS: TestRepro (0.00s)
=== RUN   TestRepro
--- PASS: TestRepro (0.00s)
PASS
```

Which is hard to improve for me :)
(that's with go 1.14.4)
