### ISSUE TITLE
HSTRLEN and HSCAN are not properly supported.

### ISSUE THREAD

**Issue by franklee0817** [alicebob/miniredis#164]
Miniredis is really wonderful for Redis mocking in the Golang unit test. I found two commands which are not properly supported during the unit test of our project. Please see under.

1. HSTRLEN is not supported now.

2. HSCAN does not properly return the pagination cursor(always return 0 and stop for none 0 cursor input). Which cause that we're not able to mock a hash tree scan page by page.

**Comment by alicebob** [comment]
> 1. HSTRLEN is not supported now.

I'll have a look at this one.

> 2. HSCAN does not properly return the pagination cursor(always return 0 and stop for none 0 cursor input). Which cause that we're not able to mock a hash tree scan page by page.

That's unfortunate. I'm not planning to implement a "proper" scan because I
expect it'll get complited with those cursors. Maybe you have any idea how to
implement scan which behaves the same way Redis does?

**Comment by alicebob** [comment]
I merged support for HSTRLEN into master, I'll make it a proper release in a week or so.

**Comment by franklee0817** [comment]
> I merged support for HSTRLEN into master, I'll make it a proper release in a week or so.

Thanks for that.
