### ISSUE TITLE
KEEPTTL not supported on SET command

### ISSUE THREAD

**Issue by johnpena** [alicebob/miniredis#177]
As of redis 6.0, the [SET](https://redis.io/commands/set) command supports a `KEEPTTL` option, which retains the TTL of the old value (in case there was one). When miniredis receives a SET command with a `KEEPTTL` option, it returns `ERR syntax error` instead of accepting the key and retaining the old TTL value (if there is one).

**Comment by alicebob** [comment]
> As of redis 6.0, the [SET](https://redis.io/commands/set) command supports a `KEEPTTL` option, which retains the TTL of the old value (in case there was one). When miniredis receives a SET command with a `KEEPTTL` option, it returns `ERR syntax error` instead of accepting the key and retaining the old TTL value (if there is one). 

Hi,
thanks for the issue! I'll see if I can add it soon.
