### ISSUE TITLE
UNSUBSCRIBE/PUNSUBSCRIBE returns no response

### ISSUE THREAD

**Issue by dearchap** [alicebob/miniredis#183]
If a client in unsubscribed from all channels and patterns sending a final "UNSUBSCRIBE" or "PUNSUBSCRIBE" causes the client to not receive a response from miniredis. The behaviour works with an actual redis server though.

**Comment by alicebob** [comment]
On Tue, Dec 22, 2020 at 08:09:54AM -0800, dearchap wrote:
> If a client in unsubscribed from all channels and patterns sending a final "UNSUBSCRIBE" or "PUNSUBSCRIBE" causes the client to not receive a response from miniredis. The behaviour works with an actual redis server though. 

Thanks for your issue. Could you add a small testcase demonstrating what you're
doing exactly? That would make fixing it much easier.

**Comment by dearchap** [comment]
Sure will do.

**Comment by dearchap** [comment]
`func TestUnsubscribeEmpty(t *testing.T) {
	s, err := Run()
	ok(t, err)
	defer s.Close()
	c, err := proto.Dial(s.Addr())
	ok(t, err)
	defer c.Close()

	mustDo(t, c,
		"UNSUBSCRIBE",
		proto.Array(
			proto.String("unsubscribe"),
			proto.Nil,
			proto.Int(0),
		),
	)
}`

**Comment by dearchap** [comment]
Similar kind of test for PUNSUBSCRIBE

**Comment by alicebob** [comment]
Hi @dearchap . Thanks for the clear test. Could you give #184 a try? Branch is called `unsub`.

**Comment by dearchap** [comment]
@alicebob This works beautifully. Thank you so much for the quick turn around time.

**Comment by alicebob** [comment]
Great, thanks for your test and testing. I merged it to master, I'll make it a new release after Christmas.
