### ISSUE TITLE
Test error in TestCmdEvalReply

### ISSUE THREAD

**Issue by eclipseo** [alicebob/miniredis#185]
On Fedora Rawhide with Golang 1.15.6:

```
--- FAIL: TestCmdEvalReply (0.01s)
    cmd_scripting_test.go:438: expected "string expected, got number" in "-1\r\n"
    cmd_scripting_test.go:448: expected "string expected, got number" in "+1\r\n"
```

**Comment by alicebob** [comment]
Thanks for the bug report. I had a quick look and can't explain this feailure, I'll have a better look soon.

**Comment by alicebob** [comment]
Thanks for the report, the fix is in master. I'll make a new release in a week or so.
