### ISSUE TITLE
Solving failure: No versions of github.com/alicebob/miniredis met constraints:

### ISSUE THREAD

**Issue by Nishanth-GH** [alicebob/miniredis#188]
I'm importing "github.com/alicebob/miniredis/v2" to mock redis cluster in units.
When i do dep ensure i'm getting the below error. I'm on Go version 1.15

Solving failure: No versions of github.com/alicebob/miniredis met constraints:
	v2.14.1: Could not introduce github.com/alicebob/miniredis@v2.14.1, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	v2.14.0: Could not introduce github.com/alicebob/miniredis@v2.14.0, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	v2.13.3: Could not introduce github.com/alicebob/miniredis@v2.13.3, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	v2.13.2: Could not introduce github.com/alicebob/miniredis@v2.13.2, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	v2.13.1: Could not introduce github.com/alicebob/miniredis@v2.13.1, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	v2.13.0: Could not introduce github.com/alicebob/miniredis@v2.13.0, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	v2.12.0: Could not introduce github.com/alicebob/miniredis@v2.12.0, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	v2.11.4: Could not introduce github.com/alicebob/miniredis@v2.11.4, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	v2.11.3: Could not introduce github.com/alicebob/miniredis@v2.11.3, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	v2.11.2: Could not introduce github.com/alicebob/miniredis@v2.11.2, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	v2.11.1: Could not introduce github.com/alicebob/miniredis@v2.11.1, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	v2.11.0: Could not introduce github.com/alicebob/miniredis@v2.11.0, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	v2.10.1: Could not introduce github.com/alicebob/miniredis@v2.10.1, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	v2.10.0: Could not introduce github.com/alicebob/miniredis@v2.10.0, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	v2.9.1: Could not introduce github.com/alicebob/miniredis@v2.9.1, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	v2.9.0: Could not introduce github.com/alicebob/miniredis@v2.9.0, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	v2.8.0: Could not introduce github.com/alicebob/miniredis@v2.8.0, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	v2.7.0: Could not introduce github.com/alicebob/miniredis@v2.7.0, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	v2.6.0: Could not introduce github.com/alicebob/miniredis@v2.6.0, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	v2.5.0: Could not introduce github.com/alicebob/miniredis@v2.5.0, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	v2.4.6: Could not introduce github.com/alicebob/miniredis@v2.4.6, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	v2.4.5: Could not introduce github.com/alicebob/miniredis@v2.4.5, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	2.4.4: Could not introduce github.com/alicebob/miniredis@2.4.4, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	2.4.3: Could not introduce github.com/alicebob/miniredis@2.4.3, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	2.4.2: Could not introduce github.com/alicebob/miniredis@2.4.2, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	2.4.1: Could not introduce github.com/alicebob/miniredis@2.4.1, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	2.4: Could not introduce github.com/alicebob/miniredis@2.4, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	2.3.2: Could not introduce github.com/alicebob/miniredis@2.3.2, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	2.3.1: Could not introduce github.com/alicebob/miniredis@2.3.1, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	2.3.0: Could not introduce github.com/alicebob/miniredis@2.3.0, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	2.2.1: Could not introduce github.com/alicebob/miniredis@2.2.1, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	2.2.0: Could not introduce github.com/alicebob/miniredis@2.2.0, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	2.1.0: Could not introduce github.com/alicebob/miniredis@2.1.0, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	2.0.0: Could not introduce github.com/alicebob/miniredis@2.0.0, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	1.0.0: Could not introduce github.com/alicebob/miniredis@1.0.0, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)
	master: Could not introduce github.com/alicebob/miniredis@master, as its subpackage github.com/alicebob/miniredis/v2 is missing. (Package is required by (root).)

**Comment by Nishanth-GH** [comment]
@alicebob

**Comment by alicebob** [comment]
Hi @Nishanth-GH. I think you don't use Go modules, am I right? I messed up the transition to modules, and miniredis only works with modules. I think it should work if you use https://github.com/alicebob/miniredis/tree/v2.7.0 since it doesn't use modules yet. See also #78.

**Comment by Nishanth-GH** [comment]
Yeah i was using dep before. I migrated my repo to use go mod where things worked as expected.
If i still want to use dep are u suggesting to use version v2.7.0?

**Comment by alicebob** [comment]
> Yeah i was using dep before. I migrated my repo to use go mod where things worked as expected.

Good!

> If i still want to use dep are u suggesting to use version v2.7.0? 

Yes, that one works without modules.
