### ISSUE TITLE
Supporting Redsync on Miniredis

### ISSUE THREAD

**Issue by lazappa** [alicebob/miniredis#189]
I am attempting to use Miniredis to test some code that makes use of the [Redsync](https://github.com/go-redsync/redsync/) library. Redsync provides distributed locking on top of Redis as described [here](https://redis.io/topics/distlock). What I found is that the attempt to unlock the Redsync mutex object works in Redis, but fails Miniredis. The unlock is accomplished via a [script](https://github.com/go-redsync/redsync/blob/v4.0.4/mutex.go#L154):
```
var deleteScript = redis.NewScript(1, `
	if redis.call("GET", KEYS[1]) == ARGV[1] then
		return redis.call("DEL", KEYS[1])
	else
		return 0
	end
`)
```
What I've found is that never succeeds in Miniredis. The value that script attempts to GET and DEL was set via a typical [SET NX](https://github.com/go-redsync/redsync/blob/v4.0.4/mutex.go#L147) command direct from the client:
```
	reply, err := conn.SetNX(m.name, value, m.expiry)

```

In debugging, I determined that when the requests are processed in Miniredis, they are looking at different data structures for the data. Digging into the code, I've found that adding the following line [here in lua.go](https://github.com/alicebob/miniredis/blob/v2.14.2/lua.go#L21) fixes the issue:
```
               pCtx.selectedDB = getCtx(c).selectedDB
```
The value of `getCtx(c).selectedDB` seems to always be `15`. Without that line added, `pCtx.selectedDB` is `0`, which digging deeper into the code seems to create a new [empty DB](https://github.com/alicebob/miniredis/blob/v2.14.2/miniredis.go#L236-L244):
```
// get DB. No locks!
func (m *Miniredis) db(i int) *RedisDB {
	if db, ok := m.dbs[i]; ok {
		return db
	}
	db := newRedisDB(i, m) // main miniredis has our mutex.
	m.dbs[i] = &db
	return &db
}
```

I'm not familiar enough with the internals of Miniredis to know why the current behavior is the default, or if there is anything that adding the fix might break. All of the unit tests still pass with that line present though. I used some test code to validate the existing failing behavior versus the fixed behavior, but I don't really know the best way to create such a scenario in the existing Miniredis tests.

**Comment by alicebob** [comment]
Hi @lazappa,

thanks for the clear explanation, with it it was easy to write a quick test, see #190. It seems indeed that miniredis doesn't set the selected database in Lua, and your fix seems correct. I'll have a 2nd look soon, and then I'll merge it.

Thanks!

**Comment by alicebob** [comment]
Sorry for the delay, should be fixed in master now.

**Comment by alicebob** [comment]
I made a release with the fix: https://github.com/alicebob/miniredis/releases/tag/v2.14.3
