### ISSUE TITLE
why set Miniredis.port as a private field

### ISSUE THREAD

**Issue by JonesSun** [alicebob/miniredis#19]
i want change the redis port to 6379  but  Miniredis.port can never set it up.

**Comment by ddatsh** [comment]
+1
add SetPort method?

**Comment by alicebob** [comment]
@JonesSun and @ddatsh: Does #20 help?

You would use it like this:
```
m := NewMiniRedis()
err := m.StartAddr("127.0.0.1:6379")
```

(or use `:6379` if you don't want to listen on localhost only)

**Comment by ddatsh** [comment]
#20 perfect
