### ISSUE TITLE
command 'EXPIRE' and  arg 'EX' not worked

### ISSUE THREAD

**Issue by wbyao** [alicebob/miniredis#197]
just the title

EXPIRE key
SET key val EX 10

**Comment by alicebob** [comment]
On Mon, Apr 05, 2021 at 06:39:41PM -0700, wbyao wrote:
> just the title
> 
> EXPIRE key
> SET key val EX 10

Hi,

thanks for the issue.
Also please read https://github.com/alicebob/miniredis#ttls-key-expiration-and-time . For expiration to work you must use "m.FastForward(d)".
If that doesn't explain it, can you show what happens and what you expected?

(and finally, be sure you import the /v2 version of miniredis)

**Comment by wbyao** [comment]
> On Mon, Apr 05, 2021 at 06:39:41PM -0700, wbyao wrote: just the title EXPIRE key SET key val EX 10
> Hi, thanks for the issue. Also please read https://github.com/alicebob/miniredis#ttls-key-expiration-and-time . For expiration to work you must use "m.FastForward(d)". If that doesn't explain it, can you show what happens and what you expected? (and finally, be sure you import the /v2 version of miniredis)

thanks for your reply

That means  i can only use "m.FastForward(d)" to update the TTL ，TTL will not update automatically?

**Comment by alicebob** [comment]
> thanks for your reply
> 
> That means  i can only use "m.FastForward(d)" to update the TTL ，TTL will not update automatically?

Correct. You'll have to call m.FastForward(d) yourself.

**Comment by wbyao** [comment]
> thanks for your reply That means i can only use "m.FastForward(d)" to update the TTL ，TTL will not update automatically?
> Correct. You'll have to call m.FastForward(d) yourself.

Fine, thanks
