### ISSUE TITLE
XREAD from non-existing stream should not result in error

### ISSUE THREAD

**Issue by svakili** [alicebob/miniredis#198]
If a stream is not existing, redis return nil, not an error:
```
> xread STREAMS nonExistingStream 0
(nil)
```
miniredis returns an error (`msgInvalidStreamID`), which is not consistent.

**Comment by alicebob** [comment]
The handling was indeed pretty broken. Could you try branch `nostream`, see it fixes it for you? Thanks!

**Comment by svakili** [comment]
Yes, I can confirm that this issue is fixed. Thank you!
