### ISSUE TITLE
After executing FLUSHALL, one can still XREAD messages from a stream

### ISSUE THREAD

**Issue by svakili** [alicebob/miniredis#204]
1 - XADD a message to a non-existing stream, called `newstream`.
2- Execute FLUSHALL.
3- XREAD messages from `newstream`.
The message added in step one still exists. In Redis, it returns nil.

**Comment by alicebob** [comment]
On Tue, May 04, 2021 at 10:01:05AM -0700, svakili wrote:
> 1 - XADD a message to a non-existing stream, called `newstream`.
> 2- Execute FLUSHALL.
> 3- XREAD messages from `newstream`.
> The message added in step one still exists. In Redis, it returns nil.

Thanks for the issue! I'll have a look soon.

**Comment by alicebob** [comment]
I got a fix in #205, but there are more cases where streams behave a bit differently. Will take a while to go through all commands in detail.

**Comment by svakili** [comment]
I can confirm that #205 has fixed the issue.

**Comment by alicebob** [comment]
thanks for the confirmation. The fix is merged to master, didn't make a release yet. There are more things which need to be checked in the streams, but if you find more problems do open some issues.

Thanks!
