### ISSUE TITLE
[feature request] Support xpending

### ISSUE THREAD

**Issue by bbedward** [alicebob/miniredis#207]
I'm using the [taskq](https://github.com/vmihailenco/taskq) package with redis backend.

It seems it doesn't work with miniredis due to lack of support for the `xpending` command:

```
taskq: 2021/05/11 13:04:53 queue.go:289: redisq: pending failed: ERR unknown command `xpending`, with args beginning with: `taskq:{api-worker}:stream`, `taskq`, `1620752993837`, `+`, `100`, 
```

It would be great if this could be supported, miniredis is great for our unit tests.

**Comment by alicebob** [comment]
Hi @bbedward,

it's should be there in the `xpend` branch. If you could give it a try that would be great. If not, also fine.

**Comment by alicebob** [comment]
Fixed, it's in master, will make a release in a week or so.
