### ISSUE TITLE
Server fails processing bulk strings larger than 4k

### ISSUE THREAD

**Issue by tobbe303** [alicebob/miniredis#21]
Attempting to rpush a string larger than 4k fails in server/proto.go/readString() since the buffer used by bufio.Read() gets full. No additional attempts to read remaining data are made and the function returns an invalid request error.

The bufio.Reader is created in server/server.go/servePeer() and defaults to 4k in buffer size.

**Comment by alicebob** [comment]
Thanks for the report! It's fixed in https://github.com/alicebob/miniredis/commit/de178b576deccc30384b631b3c5b6f6e60c98f25

with an additional proof in https://github.com/alicebob/miniredis_vs_redis/commit/479b2fbbb40dcedafbdaa85ada3cf1b7f73546f7
