### ISSUE TITLE
EVAL should cache the script

### ISSUE THREAD

**Issue by guoshimin** [alicebob/miniredis#214]
According to https://redis.io/commands/eval#script-cache-semantics, 

> Executed scripts are guaranteed to be in the script cache of a given execution of a Redis instance forever. This means that if an EVAL is performed against a Redis instance all the subsequent EVALSHA calls will succeed.

miniredis doesn't seem to cache EVAL'ed scripts.

Repro:
```
import (
	"context"
	"crypto/sha1"
	"fmt"
	"testing"

	"github.com/alicebob/miniredis/v2"
	"github.com/go-redis/redis/v8"
)

func TestEval(t *testing.T) {
	redisServer, _ := miniredis.Run()
	defer redisServer.Close()

	redisClient := redis.NewClient(&redis.Options{
		Addr: redisServer.Addr(),
	})

	ctx := context.Background()
	redisClient.Eval(ctx, "return 123", nil).Result()
	res, _ := redisClient.ScriptExists(ctx, fmt.Sprintf("%x", sha1.Sum([]byte("return 123")))).Result()
	if !res[0] {
		t.Fail()
	}
}

```

**Comment by alicebob** [comment]
On Wed, Jun 23, 2021 at 10:55:56PM -0700, Shimin Guo wrote:
> According to https://redis.io/commands/eval#script-cache-semantics, 
> 
> > Executed scripts are guaranteed to be in the script cache of a given execution of a Redis instance forever. This means that if an EVAL is performed against a Redis instance all the subsequent EVALSHA calls will succeed.
> 
> miniredis doesn't seem to cache EVAL'ed scripts.

Thanks for the report.

Interesting! Could you make a tiny example test case?

**Comment by guoshimin** [comment]
Edited the issue description to include a repro.

**Comment by alicebob** [comment]
Thanks again for the report! The linked PR fixes it for me. Will merge it to master in a few days.
