### ISSUE TITLE
A key set with EX option does not  ever expire 

### ISSUE THREAD

**Issue by shafreeck** [alicebob/miniredis#217]
1. SET key val Ex 1
2.  After 1s
3. GET key

The key is not expired.

**Comment by alicebob** [comment]
On Wed, Aug 04, 2021 at 05:46:18AM -0700, Shafreeck Sea wrote:
> 1. SET key val Ex 1
> 2.  After 1s
> 3. GET key
> 
> The key is not expired. 

Hi,
thanks for the issue.

please ensure that you:
- use the /v2 version of miniredis
- call m.FastForward() as described in https://github.com/alicebob/miniredis#ttls-key-expiration-and-time

Does that help?

**Comment by shafreeck** [comment]
It works !!! 

Thanks for your very timely response, it really helps.
