### ISSUE TITLE
redis.log not supported from lua within miniredis

### ISSUE THREAD

**Issue by dirkm** [alicebob/miniredis#228]
Against a real redis, I can use in my lua-scripts redis log like :

```
redis.log(redis.LOG_NOTICE, "script started")
```

This results in the error-message

```
lua error response ERR Error compiling script (new function): <string>:5: attempt to call a non-function object stack traceback:  <string>:5: in main chunk  [G]: ?"
```

**Comment by alicebob** [comment]
> redis.log(redis.LOG_NOTICE, "script started")

Thanks for the issue!

Should be easy enough to add. I'll have a look, but PRs are always
welcome :)

**Comment by dirkm** [comment]
I am not exactly a lua-expert but will try to write a small patch next week
