### ISSUE TITLE
command zinterstore cannot contain both zset and set keys

### ISSUE THREAD

**Issue by lingjl2010** [alicebob/miniredis#233]
command zinterstore cannot contain both zset and set keys

in redis:
```
> zadd h1 2 f1
(integer) 1
> sadd h2 f1
(integer) 1
> zinterstore dest 2 h1 h2
(integer) 1
> zrange dest 0 -1 withscores
1) "f1"
2) "3"
```

in miniredis:
```
zinterstore dest 2 h1 h2
(error) WRONGTYPE Operation against a key holding the wrong kind of value
```

**Comment by alicebob** [comment]
On Sun, Nov 14, 2021 at 05:51:39PM -0800, lingjl2010 wrote:
> in redis:
> ```
> > zadd h1 2 f1
> (integer) 1
> > sadd h2 f1
> (integer) 1
> > zinterstore dest 2 h1 h2
> (integer) 1
> > zrange dest 0 -1 withscores
> 1) "f1"
> 2) "3"
> ```
> 
> in miniredis:
> ```
> zinterstore dest 2 h1 h2
> (error) WRONGTYPE Operation against a key holding the wrong kind of value
> ```

Hi,

thank you for the bug report! I'll have a look soon.
