### ISSUE TITLE
Expire not working correctly

### ISSUE THREAD

**Issue by barthr** [alicebob/miniredis#24]
I'm working with `miniredis` inside my unit tests. And in my code I try to expire a key with a given TTL. (using `github.com/mediocregopher/radix.v2`) library for redis. But the expire won't work. When I do it using `SetTTL` it does work. But when calling it from the redis library nothing ever happens. Any suggestions on how to fix this ?

**Comment by barthr** [comment]
Never mind was mistake with different types 💯

**Comment by alicebob** [comment]
All good :)

Also, don't forget that miniredis doesn't expire keys automatically. You'll have to use `.FastForward()` and/or `.SetTime()` for TTLs to be checked.

Groeten!
