### ISSUE TITLE
COPY command not supported

### ISSUE THREAD

**Issue by rockitbaby** [alicebob/miniredis#241]
Thank you for creating miniredis!

We use miniredis for unit tests and noticed that `_, err := conn.Do("COPY", from[i], to[i])` leads to the followig error

```
ERR unknown command `COPY`, with args beginning with …
```

It seems that [COPY](https://redis.io/commands/copy) is not supported, yet.

**Comment by alicebob** [comment]
On Fri, Jan 07, 2022 at 12:27:59AM -0800, Michael Schieben wrote:
> Thank you for creating miniredis!
> 
> We use miniredis for unit tests and noticed that `_, err := conn.Do("COPY", from[i], to[i])` leads to the followig error
> 
> ```
> ERR unknown command `COPY`, with args beginning with …
> ```
> 
> It seems that [COPY](https://redis.io/commands/copy) is not supported, yet.

Hi,
thank you for creating an issue.
Good catch. I see it's introduced in:

> Available since 6.2.0

but it looks straightforward to add and I'll have a look soonish. Of course,
PRs are also accepted :)

**Comment by alicebob** [comment]
Hi, I merged @matiasinsaurralde 's PR into master. I'll make it a proper release in a week or so.

**Comment by rockitbaby** [comment]
@alicebob thank you for your prompt responses and once again, thanks @matiasinsaurralde

**Comment by wszaranski** [comment]
@alicebob since https://github.com/alicebob/miniredis/pull/244 was merged and there was no further discussion in this issue I think it can be closed.
