### ISSUE TITLE
wrong result for BITCOUNT with MAX value MAX_INT64

### ISSUE THREAD

**Issue by dirkm** [alicebob/miniredis#250]
There is a small discrepancy in BITCOUNT for the corner-case below:

against miniredis

```
dirk@tux0058:~/repo/miniredis$ redis-cli -h 127.0.0.1 -p 42317
127.0.0.1:42317> SETBIT "A" 10 1
(integer) 1
127.0.0.1:42317> BITCOUNT "A" 0 100000
(integer) 1
127.0.0.1:42317> BITCOUNT "A" 0 9223372036854775807
(integer) 0
```

against redis

```
dirk@tux0058:~/repo/redis$ redis-cli 
127.0.0.1:6379> SETBIT "A" 10 1
(integer) 0
127.0.0.1:6379> BITCOUNT "A" 0 100000
(integer) 1
127.0.0.1:6379> BITCOUNT "A" 0 9223372036854775807
(integer) 1
127.0.0.1:6379> 
```

Note that BITCOUNT returns the value 0 when MAX is set to MAX_INT64. A real redis-server (6.0.15) returns the correct value 1.

**Comment by alicebob** [comment]
> Note that BITCOUNT returns the value 0 when MAX is set to MAX_INT64. A real redis-server (6.0.15) returns the correct value 1.

Fun one, thanks!
I'll have a look soon. Don't think  the bitcount things are used a lot :)

**Comment by alicebob** [comment]
Thanks! It's now fixed in master, will make it a new release in a week or so. It was a `max++` somewhere, which overflowed :(
