### ISSUE TITLE
LPOS is not supported command for LISTs

### ISSUE THREAD

**Issue by bpatel85** [alicebob/miniredis#253]
`LPOS` is the command to return the index of matching elements inside a Redis list. It doesn't seem to supported at the moment.
https://redis.io/commands/lpos

Wondering whether there are plans to add it.

**Comment by bpatel85** [comment]
`LMPOP`, `BLMOVE` and `BLMPOP` are some other that I discovered are not supported.

**Comment by alicebob** [comment]
Thanks for your issue!

> Available since 6.0.6.

that explains, it got added after we added the other L commands, and since then no-one asked for it.

There are no concrete plans, but they are likely not hard to add, and I will have a look when I have some time. PRs are always welcome as well, of course.

**Comment by ianstarz** [comment]
In progress https://github.com/alicebob/miniredis/compare/master...ianstarz:miniredis:lpos?expand=1

I should be able to finish this up by next week.

**Comment by ianstarz** [comment]
Ready for review
