### ISSUE TITLE
Support command XAUTOCLAIM

### ISSUE THREAD

**Issue by vrecan** [alicebob/miniredis#254]
We leverage streams and the auto claim functionality, it would be great if miniredis supported this. It would allow us to write unit tests instead of integration tests around this functionality.

**Comment by alicebob** [comment]
On Thu, Feb 10, 2022 at 08:43:40AM -0800, Ben Aldrich wrote:
> We leverage streams and the auto claim functionality, it would be great if miniredis supported this. It would allow us to write unit tests instead of integration tests around this functionality.

Hi,
thanks for your issue.
I'll put it on my list, but of course a PR is also always welcome :)

**Comment by randall-fulton** [comment]
@alicebob Had the same problem as @vrecan and a little spare time to try to knock this out.

**Comment by wszaranski** [comment]
@vrecan Is there anything left to do for this issue to be closed?
@alicebob I think it can be closed as resolved.
