### ISSUE TITLE
ZRange not fully support when running in a LUA script

### ISSUE THREAD

**Issue by valdemarpereira** [alicebob/miniredis#257]
I'm correct to assume the `zrange` command is not fully supported if used inside a LUA script?  
If the run the following examples:

```
"redis.call('zrange', 'myzset', '1', '5', 'BYSCORE');"
"redis.call('zrange', 'myzset', '(1', '5');"
"redis.call('zrange', 'myzset', '-inf', '5');"

```
I get the following error:
```
ERR Error compiling script (new function): <string>:1: ERR syntax error stack traceback:  [G]: in function 'call'  <string>:1: in main chunk  [G]: ?
```

Only the most basic example seem to work:
```
"redis.call('zrange', 'myzset', '1', '5');"
```

**Comment by alicebob** [comment]
On Tue, Mar 01, 2022 at 07:57:10AM -0800, Valdemar Pereira wrote:
> I'm correct to assume the `zrange` command is not fully supported if used inside a LUA script?  

That looks weird. I see no reason why it shouldn't be.

> If the run the following examples:
> 
> ```
> "redis.call('zrange', 'myzset', '1', '5', 'BYSCORE');"
> "redis.call('zrange', 'myzset', '(1', '5',);"

not sure that last ',' is valid.

> "redis.call('zrange', 'myzset', '-inf', '5');"
> 
> ```
> I get the following error:
> ```

**Comment by valdemarpereira** [comment]
that `,` was a typo from my end. I updated the issue.
Could you please quickly try it on your end? any of the 3 examples fail...

**Comment by alicebob** [comment]
Should be fixed in master.

Note that this example:
> "redis.call('zrange', 'myzset', '(1', '5');"

won't work. That's not a valid zrange command, it needs to have "BYSCORE":
```
127.0.0.1:6379> zrange myset (1 5
(error) ERR value is not an integer or out of range
127.0.0.1:6379> zrange myset (1 5 byscore
(empty array)
```
