### ISSUE TITLE
not support setnx with ttl?

### ISSUE THREAD

**Issue by g10guang** [alicebob/miniredis#259]

**Comment by alicebob** [comment]
> not support setnx with ttl? (Issue #259)

Hi,

thank you for opening an issue.

I don't understand what you're asking. Can you point to the documentation on
the redis.io site? Maybe somewhere here: https://redis.io/commands/setnx

Thanks!

**Comment by rentiansheng** [comment]
use 	"github.com/gomodule/redigo/redis  exec redis command  Do("SET", "key", "value", "PX", int64(expire), "nx")

expire not work. but using a physical Redis server is ok


 
Playground: 
https://go.dev/play/p/2VEvoPXkQLc

**Comment by alicebob** [comment]
Thanks for the clarification. That's what @ChaosNyaruko was going for, please check https://github.com/alicebob/miniredis#ttls-key-expiration-and-time

**Comment by rentiansheng** [comment]
> Thanks for the clarification. That's what @ChaosNyaruko was going for, please check https://github.com/alicebob/miniredis#ttls-key-expiration-and-time

I called the function  FastForward.   TTL is decrease when TTL is equal 0,   exec command  "Do("SET", "key", "value", "PX", int64(expire), "nx")" miniredis  reply is not ok

**Comment by alicebob** [comment]
Hi,

thanks for your clarification.

You use: `redis.FastForward(1)`, which is 1 nanosecond.
It works if you use this:
``` 
    // time.Sleep(time.Second * 1)
    mockRedis.FastForward(1 * time.Second)
```
That gives me:
```
start
ttl1 1 ttl2 -2
```

(note that you don't need to call time.Sleep())

**Comment by rentiansheng** [comment]
☕️。 thanks
