### ISSUE TITLE
GT and LT options for ZADD command

### ISSUE THREAD

**Issue by lsgndln** [alicebob/miniredis#266]
Hey :)

It seems that I have a syntax error when using `GT` and `LT` options for the [ZADD](https://redis.io/commands/zadd/) command.

Is it supported ? Thankst !

**Comment by lsgndln** [comment]
I created a [PR](https://github.com/alicebob/miniredis/pull/267) if that helps. Not sure how to properly test though.

**Comment by alicebob** [comment]
thanks for the easy PR!

**Comment by alicebob** [comment]
> It seems that I have a syntax error when using `GT` and `LT` options for the `[ZADD](https://redis.io/commands/zadd/)` command.
> 
> Is it supported ? Thankst !

They got added later, and support needs to be added.
From the docs:

> Starting with Redis version 6.2.0: Added the GT and LT options

I can have a look another day, but of course a PR is always welcome as well :)
