### ISSUE TITLE
get miniredis using go get

### ISSUE THREAD

**Issue by nishanth5028** [alicebob/miniredis#270]
I’m trying to fetch the latest version of miniredis using go get. However i run into the issue 

`go get github.com/alicebob/miniredis@v2.21.0: github.com/alicebob/miniredis@v2.21.0: invalid version: unknown version v2.21.0 `

I see that the suggested way to use is import “github.com/alicebob/miniredis/v2” , however how do we get the latest version to use the v2 module.

**Comment by alicebob** [comment]
> `go get ***@***.***: ***@***.***: invalid version: unknown version v2.21.0 `
> 
> I see that the suggested way to use is import “github.com/alicebob/miniredis/v2” , however how do we get the latest version to use the v2 module. 

Which version of Go are you using? I don't thing it still works with a
pre-modules version of Go (I messed up the transition to V2 back then)

**Comment by nishanth5028** [comment]
I am using 1.17 version

**Comment by nishanth5028** [comment]
I was using the wrong command . The below command worked
`go get github.com/alicebob/miniredis/v2`
