### ISSUE TITLE
MEMORY USAGE command

### ISSUE THREAD

**Issue by arielzach** [alicebob/miniredis#295]
Hi,

Is it possible to add the MEMORY USAGE command? It currently returns 0.

**Comment by wszaranski** [comment]
@alicebob I think this issue can be closed since [Memory Usage #341](https://github.com/alicebob/miniredis/pull/341) was merged and released in [v2.31.0](https://github.com/alicebob/miniredis/blob/master/CHANGELOG.md#v2310).
