### ISSUE TITLE
ZADD INCR support?

### ISSUE THREAD

**Issue by matwalsh** [alicebob/miniredis#30]
Looking over https://redis.io/commands/zadd it seems like a command in the form of
`ZADD key INCR value field`
should work.

There doesn't seem to be support for that in https://github.com/alicebob/miniredis/blob/master/cmd_sorted_set.go#L60-L89 resulting in
> value is not a valid float

when line 80 tries to parse "INCR" as a float.

`ZINCRBY` does seem to work as an alternative, but are there plans to add support for the ZADD version?

**Comment by alicebob** [comment]
Seems like I missed when 'INCR' got added. I'll add support for it soon; looks easy enough.

**Comment by matwalsh** [comment]
Awesome!  Thanks.

**Comment by alicebob** [comment]
Thanks for the report. I just released version 2.3.2 which has the missing 'INCR' flag.

I looked through all other Redis `Z*` commands and they seem to match the documentation, but do let me know if you find something weird!
