### ISSUE TITLE
support for redis v8 

### ISSUE THREAD

**Issue by Manask322** [alicebob/miniredis#302]
Could you please state any timelines to support miniredis to support https://github.com/go-redis/redis

**Comment by alicebob** [comment]
On Tue, Nov 01, 2022 at 11:50:40AM -0700, Manask322 wrote:
> Could you please state any timelines to support miniredis to support https://github.com/go-redis/redis

There is no defined timeline, it's completely best effort. But v8 isn't that
different from v7, so I expect the v8 client to work, unless you're using
funky stuff.

**Comment by alicebob** [comment]
Miniredis now targets Redis 7.0
