### ISSUE TITLE
ZMSCORE unsupported

### ISSUE THREAD

**Issue by tonyhb** [alicebob/miniredis#310]
ZMSCORE has existed in redis since v6.2.0 (https://redis.io/commands/zmscore/), but is unimplemented in miniredis

**Comment by alicebob** [comment]
Hi, thanks for your issue. Maybe I get around to this one day, but if you need it soon the quickest way is to make a PR.

**Comment by tonyhb** [comment]
Was thinking the same thing, and will look if and when I need to add it :)

**Comment by sejin-P** [comment]
I think this has been resolved by https://github.com/alicebob/miniredis/pull/329.
