### ISSUE TITLE
expire time invalid

### ISSUE THREAD

**Issue by maxiye** [alicebob/miniredis#312]

**Comment by alicebob** [comment]
Hi @maxiye, thank you for your issue. Can you explain the problem?

**Comment by maxiye** [comment]
<img width="413" alt="image" src="https://user-images.githubusercontent.com/23513922/212059957-74cbf52f-7028-4e31-bd65-7fa8ef1d9e3d.png">

**Comment by maxiye** [comment]
@alicebob pls

**Comment by alicebob** [comment]
If you want to use expiration times you have to use `m.FastForward(2 * time.Second)`, not `time.Sleep(2*time.Second)`. Miniredis does not expire keys automatically, but only when calling FastForward.

**Comment by maxiye** [comment]
thank u, i got
