### ISSUE TITLE
Wrong behavior with SET NX GET

### ISSUE THREAD

**Issue by hongyiweiwu** [alicebob/miniredis#315]
According to Redis specification, if we specify NX with GET in a SET command, even if the condition for NX is not met and the value is not set, we still return the old value instead of returning a `nil`:

https://redis.io/commands/set/
```
[Null reply](https://redis.io/docs/reference/protocol-spec#resp-bulk-strings): (nil) if the SET operation was not performed because the user specified the NX or XX option but the condition was not met.

If the command is issued with the GET option, the above does not apply. It will instead reply as follows, regardless if the SET was actually performed:

[Bulk string reply](https://redis.io/docs/reference/protocol-spec#resp-bulk-strings): the old string value stored at key.

[Null reply](https://redis.io/docs/reference/protocol-spec#resp-bulk-strings): (nil) if the key did not exist.
```

However, it doesn't seem like the behavior is followed [here](https://github.com/alicebob/miniredis/blob/master/cmd_string.go#L134): the function immediately returns with a `nil` value without checking whether `GET` is set.

**Comment by alicebob** [comment]
On Mon, Mar 06, 2023 at 05:30:19PM -0800, hongyiweiwu wrote:
> According to Redis specification, if we specify NX with GET in a SET command, even if the condition for NX is not met and the value is not set, we still return the old value instead of returning a `nil`:

Hi,

thank you for your issue and clear description. I'll have a look soon, but if
you want you can also try to submit a PR to fix it.

**Comment by hongyiweiwu** [comment]
Hey, sorry I was swamped with work yesterday so didn't have a chance to write a PR. Thanks for this fix, it looks great!

**Comment by alicebob** [comment]
No problem, thanks for the issue. New release with this:  v2.30.1
