### ISSUE TITLE
how can i know the miniredis was close

### ISSUE THREAD

**Issue by welldonexing** [alicebob/miniredis#317]
go func() {
		for {
			time.Sleep(1 * time.Second)
			s.FastForward(1 * time.Second)
		}

	}()

as i was start the loop  to clear the ttl , when i call  s.close . this still walking  and  still have data , does it have menory leak  or  how can i destroy totally  or  how can i know the  s.    was close.

**Comment by alicebob** [comment]
You could use a context. Something along these lines:

```

ctx, cancel := context.WithCancel(context.Background())
defer cancel()
s, err  := miniredis.Run()
if err ...
go func() {
loop:
    for {
        select {
            case <- ctx.Done():
               break loop
            default:
        }
       time.Sleep(time.Second)
       s.FastForward(time.Second)
    }
    s.Close()
}()

...
```

**Comment by welldonexing** [comment]
thank you very much and my solution 
	go func() {
		for {
			time.Sleep(2 * time.Second)
			s.FastForward(2 * time.Second)
			if s.Server() == nil {
				println("redis server down \n")
				break
			}
		}

	}()
