### ISSUE TITLE
Does not build with Go 1.8?

### ISSUE THREAD

**Issue by danikalmar** [alicebob/miniredis#32]
I was trying to build it with Go 1.8.3, and always got the following errors:

`../../_vendor/src/github.com/alicebob/miniredis/test.go:10: tb.Helper undefined (type testing.TB has no field or method Helper)
../../_vendor/src/github.com/alicebob/miniredis/test.go:19: tb.Helper undefined (type testing.TB has no field or method Helper)
../../_vendor/src/github.com/alicebob/miniredis/test.go:28: tb.Helper undefined (type testing.TB has no field or method Helper)
../../_vendor/src/github.com/alicebob/miniredis/test.go:37: tb.Helper undefined (type testing.TB has no field or method Helper)`

I found this [issue](https://github.com/hetznercloud/terraform-provider-hcloud/issues/8), which seems related.

**Comment by danikalmar** [comment]
I managed to build it successfully with Go 1.9.4.

**Comment by alicebob** [comment]
As mentioned in #33, fixed with https://github.com/alicebob/miniredis/commit/ba1c4425087c2209d30c0a88b09e26387df2fe73

Thanks!
