### ISSUE TITLE
Blocking calls from lua always deadlock

### ISSUE THREAD

**Issue by logan** [alicebob/miniredis#326]
Lua scripts are executed while Miniredis is locked. If a script calls a blocking command (in my case, XReadGroup), it will never return because the the blocking signal uses the same mutex.

```go
package scripts

import (
	"context"
	"testing"

	"github.com/alicebob/miniredis/v2"
	"github.com/go-redis/redis/v8"
)

func TestLuaBlocking(t *testing.T) {
	mr, err := miniredis.Run()
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(mr.Close)
	client := redis.NewClient(&redis.Options{Addr: mr.Addr()})
	ctx := context.Background()
	if err := client.XGroupCreateMkStream(ctx, "stream", "group", "0").Err(); err != nil {
		t.Fatal(err)
	}
	if err := client.XAdd(ctx, &redis.XAddArgs{
		Stream: "stream",
		ID:     "*",
		Values: []any{"name", "value"},
	}).Err(); err != nil {
		t.Fatal(err)
	}
	t.Logf("added message")
	script := redis.NewScript(`return redis.call("XREADGROUP", "GROUP", "group", "consumer", "BLOCK", 1000, "STREAMS", "stream", ">")`)
	_, err = script.Run(context.Background(), client, []string{"stream"}).Slice()
	t.Logf("script returned")
	if err != nil {
		t.Fatal(err)
	}
}
```

In this example, the test times out because `mr.Close()` never returns. If I omit that `t.Cleanup` line then the test fails due to the "i/o timeout" error. If I omit the "BLOCK 1000" args the test passes trivially.

**Comment by alicebob** [comment]
On Fri, Apr 28, 2023 at 12:11:49PM -0700, Logan Hanks wrote:
> Lua scripts are executed while Miniredis is locked. If a script calls a blocking command (in my case, XReadGroup), it will never return because the the blocking signal uses the same mutex.

oops.
Thanks for the clear test case. I'll have a look soon (but PRs are always
accepted :)

**Comment by alicebob** [comment]
Probably fixed in the linked PR.

It doesn't hang anymore, but you do get the nice "ERR XREADGROUP command is not allowed with BLOCK option from scripts" error.

**Comment by logan** [comment]
Ah, good point, I probably should not be trying to do this. Having an explicit immediate error would keep me on the right track. :)

**Comment by alicebob** [comment]
Good to fix anyway. It's merged into master, will make it a proper version in a few days or so.
