### ISSUE TITLE
Discrepancy with LSET after copying a list

### ISSUE THREAD

**Issue by jerargus** [alicebob/miniredis#331]
Using COPY on a list key, followed by a LSET on the original list modifies the copied list as well. This unit test added to cmd_generic_test.go:TestCopy demonstrates the problem: 

```
	t.Run("list", func(t *testing.T) {
		must1(t, c, "LPUSH", "l1", "original")
		must1(t, c, "COPY", "l1", "l2")
		mustOK(t, c, "LSET", "l1", "0", "modified")
		s.CheckList(t, "l1", "modified")
		s.CheckList(t, "l2", "original")
	})
```

I believe the problem is in [minredis.go:679-680](https://github.com/alicebob/miniredis/blob/master/miniredis.go#L679-L680). After that assignment, both lists are pointing at the same block of memory, so modifying the original also modifies the copy. Go's built in 'copy' will fix this:

```
	case "list":
		destDB.listKeys[dst] = make(listKey, len(srcDB.listKeys[src]))
		copy(destDB.listKeys[dst], srcDB.listKeys[src])
```

For completeness, this integration test in generic_test.go:TestCopy also demonstrates the bug:

```
		t.Run("list set", func(t *testing.T) {
			c.Do("LPUSH", "list", "aap", "noot", "mies")
			c.Do("COPY", "list", "list2")
			c.Do("TYPE", "list2")
			c.Do("LSET", "list", "1", "vuur")
			c.Do("LRANGE", "list", "0", "-1")
			c.Do("LRANGE", "list2", "0", "-1")
		})
```

Also, thank you so much for miniredis. I love it.

**Comment by alicebob** [comment]
Hi,

thank you for your issue and thanks for the compliment! If you want you can make a PR for this, your fix looks good to me. Otherwise I'll do it in a few days.

**Comment by alicebob** [comment]
thanks for the issue. should be fixed in master
