### ISSUE TITLE
undefined: redis.Int64s

### ISSUE THREAD

**Issue by Charleslvn** [alicebob/miniredis#34]
With:
go 1.9.4 x86_64
github.com/alicebob/miniredis 2.3.2

Hello,
I try to build and test your project and it fails with :

> FAIL    github.com/alicebob/miniredis [build failed]
> # github.com/alicebob/miniredis
> ./cmd_scripting_test.go:107:13: undefined: redis.Int64s
> ./cmd_scripting_test.go:119:13: undefined: redis.Int64s
> ./cmd_scripting_test.go:125:13: undefined: redis.Int64s

Could you help me please ?

Thanks

**Comment by alicebob** [comment]
I think you have an old version of `github.com/garyburd/redigo/redis`. Try running `go get -u -v -t`
