### ISSUE TITLE
Feature Request: `CLIENT` Command Not Supported

### ISSUE THREAD

**Issue by bliutech** [alicebob/miniredis#340]
I am interested in seeing support for the `CLIENT` command. Particularly for the use cases of [`CLIENT SETNAME`](https://redis.io/commands/client-setname/) and [`CLIENT GETNAME`](https://redis.io/commands/client-getname/). I noticed that this was included in the list of commands that will probably [not be supported](https://redis.io/commands/client-getname/). I am curious as to why this is the case because `miniredis` already seems to attempt to distinguish between peers and track at least the number of clients with `INFO` and this seems like something that would be a reasonable use case. Particularly, I am running into the issue with developing functional tests with [`go-redis`](https://github.com/redis/go-redis) as [`ClusterName`](https://github.com/redis/go-redis/blob/master/cluster.go#L33) is a reasonable field that could be set.

**Comment by alicebob** [comment]
On Fri, Aug 18, 2023 at 12:34:43PM -0700, Benson Liu wrote:
> I am interested in seeing support for the `CLIENT` command. Particularly for the use cases of [`CLIENT SETNAME`](https://redis.io/commands/client-setname/) and [`CLIENT GETNAME`](https://redis.io/commands/client-getname/). I noticed that this was included in the list of commands that will probably [not be supported](https://redis.io/commands/client-getname/). I am curious as to why this is the case because `miniredis` already seems to attempt to distinguish between peers and track at least the number of clients with `INFO` and this seems like something that would be a reasonable use case. Particularly, I am running into the issue with developing functional tests with [`go-redis`](https://github.com/redis/go-redis) as [`ClusterName`](https://github.com/redis/go-redis/blob/master/cluster.go#L33) is a reasonable field that could be set.

The "not be supported" list is ancient, so take it with a grain of salt. The
`CLIENT GET/SETNAME` command looks useful. I might have a look (it sounds
easy), but if you want to try a PR that would probably be the quickest way.
