### ISSUE TITLE
Feature Request: ZINTER command

### ISSUE THREAD

**Issue by conradhanson** [alicebob/miniredis#349]
[Redis ZINTER command](https://redis.io/commands/zinter/)

`ZINTERSTORE` is supported but not `ZINTER`. Would be nice to see the latter implemented as well. 

Only difference between the two is storing the sorted set vs returning it to the client. Since they are so similar I'd think we might be able to reuse some of the current `ZINTERSCORE` logic to implement `ZINTER`.

**Comment by alicebob** [comment]
Agree, I added it in #350

**Comment by alicebob** [comment]
merged to master, will make it a proper versioned release in a few days.
