### ISSUE TITLE
Simulate server unavailable?

### ISSUE THREAD

**Issue by elliotchance** [alicebob/miniredis#36]
I have a health check that pings redis to make sure it's alive. How do I configure or mock miniredis to pretend that is unavailable/unresponsive? Also specifying a timeout on the request?

**Comment by alicebob** [comment]
Interesting idea. With ping you mean a TCP ping, or something which executes the redis PING command?

We could add a configurable delay in the server before accepting a new connection, or in the middle of the execution of a command (say put a `time.Sleep` [here](https://github.com/alicebob/miniredis/blob/master/server/server.go#L127), which is after reading the command, but before executing it)

**Comment by warijo** [comment]
Hi alicebob,

the idea is to have the ability to test your code against unexpected disconnects (e.g. cases where a `dial tcp :6379: connect: connection refused` error is returned).

For this reason it would be great, if you could "flip a switch" to tell miniredis to return above error for all calls.

**Comment by elliotchance** [comment]
This is the original issue that made me create https://github.com/elliotchance/redismock. However, as @warijo says a switch to indicate that redis is unavailable would be helpful.

**Comment by alicebob** [comment]
It sounds useful and simple enough. Could either of you give some example methods how you would like miniredis to work? Just the method signatures should be enough.

**Comment by warijo** [comment]
assuming 
`mr, _ := miniredis.Run()`
how about
`mr.SetIsConnected(false)`
or
`mr.ReturnConnectionError(true)`

after that, I would expect all calls to miniredis to return an error like the one I mentioned above

**Comment by alicebob** [comment]
On Wed, Jun 10, 2020 at 07:00:29AM -0700, warijo wrote:
> I wasn't aware of the existence of those methods. As they already exist, I'm not sure how much sense it makes to wrap an additional SetError()-method around them. Maybe a short additional entry in the README on how to simulate server-unavailability would be enough?

ok, can do that!
I do think SetError() is useful to simulate "loading" state, but that has
nothing to do with the connection.

> One last thing: miniredis behaves a bit differently than the actual redis implementation regarding connection aborts. When I tested my productive service against connection aborts, I would get an EOF error, after the connection to redis had crashed. The reason seems to be that the connection is "broken" and needs to be removed from the connection pool. Check [here](https://github.com/go-redis/redis/issues/84#issuecomment-90394588) for a discussion about this issue.

ok, I can have a look at that. I guess the shutdown in Miniredis is too nice.

Thanks for the feedback!

**Comment by alicebob** [comment]
> One last thing: miniredis behaves a bit differently than the actual redis implementation regarding connection aborts. When I tested my productive service against connection aborts, I would get an EOF error, after the connection to redis had crashed. 

I can't replicate that; I also get the EOF in miniredis:

import (
    goredis "github.com/go-redis/redis/v7"
)
func TestRestart2(t *testing.T) {
    s, err := Run()
    ok(t, err)

    s.Set("color", "red")

    c := goredis.NewClient(&goredis.Options{
        Addr: s.Addr(),
    })

    _, err = c.Ping().Result()
    ok(t, err)

    s.Close()
    ok(t, s.Restart())

    _, err = c.Ping().Result()
    ok(t, err)
}

returns:
--- FAIL: TestRestart2 (0.00s)
    miniredis_test.go:92: unexpected error: EOF

(same with v8)
What am I doing differently?

**Comment by warijo** [comment]
I just tried to reproduce it as well, and wasn't able to (I get the EOF now as well). My only guess is that I tested it with my implementation and forgot to remove the `MaxRetries`-param from the go-redis client. Sorry for wasting your time.

**Comment by alicebob** [comment]
> I just tried to reproduce it as well, and wasn't able to (I get the EOF now as well). My only guess is that I tested it with my implementation and forgot to remove the `MaxRetries`-param from the go-redis client. Sorry for wasting your time.

No problem! It's always useful to double check things anyway :)
