### ISSUE TITLE
ZRank and ZRevRank don't support WITHSCORE

### ISSUE THREAD

**Issue by jehowell** [alicebob/miniredis#385]
If you add WITHSCORE to the args, you get a ERR syntax error:

docs: https://redis.io/docs/latest/commands/zrevrank/

**Comment by alicebob** [comment]
thank for the issue. I'll have a look, but if you want you can try making a PR, it's probably faster :)

**Comment by jehowell** [comment]
#386
 Made a pull request.

**Comment by alicebob** [comment]
thanks!
