### ISSUE TITLE
Error compiling script

### ISSUE THREAD

**Issue by ppontryagin** [alicebob/miniredis#39]
1. I start redis server:
```
redisServer, err = miniredis.Run()
redisServer.RequireAuth(redisPassword)
```
2. Create a connection:
```
conn, err := redigo.Dial("tcp", addr, redigo.DialPassword(redisPassword),
					redigo.DialConnectTimeout(5*time.Second))
```

3. Create a stored procedure:
```
const getScript = `
return redis.call("GET",KEYS[1])
`
storedProcGet = redis.NewScript(1, getScript)
```

4. And when I execute it:
`_, err = storedProcGet.Do(conn, "key")`

I get:

`    ERR Error compiling script (new function): <string>:2: NOAUTH Authentication required. stack traceback:  [G]: in function 'call'  <`

However if I disable authentication or use real Redis, everything is fine.

Could you please look at that?

**Comment by ppontryagin** [comment]
Thank you, it helps!
+1

**Comment by alicebob** [comment]
merged, thanks again! Let me know if you have other problems with the Lua integration. It's rather new code.
