### ISSUE TITLE
XTRIM using wrong id comparison

### ISSUE THREAD

**Issue by daniel-cohere** [alicebob/miniredis#392]
Hi! It appears that XTRIM is using the wrong id comparison when passing a MINID. For example if there are the following ids:

`1-1`
`1-2`
`1-11`

If you execute an XTRIM with MINID = `1-11`, it won't remove `1-2` from the stream. I don't have permission to open a PR but I forked and made a fix here: https://github.com/alicebob/miniredis/pull/391/files

Would you be able to incorporate these changes into this repo?

**Comment by daniel-cohere** [comment]
Oh I guess I was able to open a PR 😅

**Comment by alicebob** [comment]
Doesn't surprise me there are some issues in there :)

Thanks for the fix!
