### ISSUE TITLE
Error happens when SET big size bytes in miniredis.

### ISSUE THREAD

**Issue by BaochunLiuBJ** [alicebob/miniredis#41]
When using _github.com/gomodule/redigo/redis_ to store a byte array whose length exceeds 10K, the following error happen: 
**write tcp 127.0.0.1:60940->127.0.0.1:40545: write: connection reset by peer**
Does miniredis has a limit on the size of the value?

**Comment by alicebob** [comment]
Hi,

thanks for your bugreport.
There should not be a size limit. You store a simple 10K byte array with a simple `SET` command?

This test passes fine:
```
func TestSetLong(t *testing.T) {
    payload := strings.Repeat("x", 10*1024*1024)
    testCommands(t,
        succ("SET", "bytes", payload),
        succ("GET", "bytes"),
    )
}
```
(that's a 10MB payload)

**Comment by BaochunLiuBJ** [comment]
The codes are like 

```
func TestSomething(t *testing.T) {
	s, err := miniredis.Run()
	if err != nil {
		panic(err)
	}
	defer s.Close()

	// Run your code and see if it behaves.
	// An example using the redigo library from "github.com/gomodule/redigo/redis":
	payload := strings.Repeat("x", 10*1024)

	c, err := redis.Dial("tcp", s.Addr())
	_, err = c.Do("SET", "foo", payload)

	r, getErr := c.Do("get","foo")
	if getErr != nil {
		t.Error("Error %v", getErr)
	}

	bytes := r.([]byte)

	if len(bytes) != 10*1024 {
		t.Error("the lenght is not right")
	}
}
```
When using go-redis as client, the same error.

**Comment by alicebob** [comment]
That test works fine for me:
```
$ go test -v -run TestSomething
=== RUN   TestSomething
--- PASS: TestSomething (0.00s)
PASS
ok  	github.com/alicebob/miniredis	0.003s
```

which OS do you use?

**Comment by BaochunLiuBJ** [comment]
mac os 10.13.4

**Comment by BaochunLiuBJ** [comment]
When upgrading miniredis to 2.3.0, it has no the issue. 
The project that i am working depends on go 1.8.5, while miniredis 2.3.0 depends on go 1.9.
When I delete miniredis/test.go of 2.3.0, and use go 1.8.5, there is no issue. 

I think the issue only exists in my case. So close this issue. 
Thanks alicebob.

**Comment by alicebob** [comment]
Happy it worked. As you noticed, it's only the tests which need 1.9.
