### ISSUE TITLE
ZADD unable to produce error

### ISSUE THREAD

**Issue by azerlinda** [alicebob/miniredis#42]
Hello,
I can't seem to produce an error after using `ZADD` for my unit test. I tried to `SET` a key and then use the same key with `ZADD`, which works when i tried it in redis, giving `WRONGTYPE Operation against a key holding the wrong kind of value` error. However, it doesn't give an error when i did the same with miniredis.

I believe there is something wrong with [this](https://github.com/alicebob/miniredis/blob/master/direct.go#L473) condition because i don't think there's a way to trigger both `db.exists(k)` and `!db.exists(k) ` at the same time. Can you please check it?

Thanks

**Comment by alicebob** [comment]
Thank you for the report!

Your assessment makes sense. I've pushed a fix to master.
Thanks!
