### ISSUE TITLE
Type mapping from Redis to Lua  is not in contract with the official Implementation

### ISSUE THREAD

**Issue by tamaseger81** [alicebob/miniredis#43]
According to the corresponding section (https://redis.io/commands/eval#conversion-between-lua-and-redis-data-types) of the official documentation, Redis `nil` would be mapped as Lua `false`.

The current implementation is appear to be mapping it as `nil` which breaks the Lua scripts expecting `false`.
https://github.com/alicebob/miniredis/blob/d5d65060a2d8061f5a4f266bc4fb20ac1091f99d/lua.go#L166

**Comment by alicebob** [comment]
Thanks for the report!

I think the above changes fixes it, but I'll have a second look later.

**Comment by tamaseger81** [comment]
Thanks @alicebob 

As a workaround the following could be used for the cost of an extra compare per check.
`local exists = redis.call('ZSCORE', KEYS[1], ARGV[1])`
`return exists ~= nil and exists ~= false`

**Comment by alicebob** [comment]
Merged to master as 2.4.4, thanks again.

If you find more Lua discrepancies let me know. That code is relatively new, and I don't use it a lot myself.
