### ISSUE TITLE
redis.replicate_commands() in LUA script causes compilation error

### ISSUE THREAD

**Issue by wushumin** [alicebob/miniredis#44]
Should be safe to ignore/perform no-op for all replication related commands?

**Comment by alicebob** [comment]
Thanks for the issue! I think you might have a point, I'll try to have a look later this week.

**Comment by alicebob** [comment]
I merged it to master, will make it a proper release laster. If there are any redis commands you think could be ignored, feel free to make an issue for them!

Thanks!
