### ISSUE TITLE
EXPIRE not working with lua script

### ISSUE THREAD

**Issue by blockloop** [alicebob/miniredis#48]
I'm running the following lua script as a ratelimiter by IP address

```
local limit = tonumber(ARGV[1])
local ttl = tonumber(ARGV[2])
local k = "requests:" .. KEYS[1]

local current = redis.call("LLEN", k)
if current >= limit then
    return redis.error_reply("too many requests")
else
    if redis.call("EXISTS", k) == 0 then
	redis.call("RPUSH", k, 1)
	redis.call("EXPIRE", k, ttl)
    else
	redis.call("RPUSHX", k, 1)
    end
end
```

using redigo, I execute `scpt.Do(con, "127.0.0.1", 1, 1)` which should create a new key at "requests:127.0.0.1" with a TTL of 1. It appears to do this much, however the key never seems to expire. Whenever I make a second call with the exact same params I'm hitting `too many requests` which should not be the case since the key should have expired. I've tried to add `time.Sleep(time.Second)` in my test, however no matter how long it sleeps the key never expires. 

If I switch to a live redis instance on my local machine my tests pass.

Here is a simple test to show the issue
```
package main

import (
	"fmt"
	"time"

	"github.com/alicebob/miniredis"
	"github.com/garyburd/redigo/redis"
)

var scpt = redis.NewScript(1, `
local limit = tonumber(ARGV[1])
local ttl = tonumber(ARGV[2])
local k = "requests:" .. KEYS[1]

local current = redis.call("LLEN", k)
if current >= limit then
    return redis.error_reply("too many requests")
else
    if redis.call("EXISTS", k) == 1 then
	redis.call("RPUSHX", k, 1)
    else
	redis.call("RPUSH", k, 1)
	redis.call("EXPIRE", k, ttl)
    end
end
`)

func main() {
	srv, _ := miniredis.Run()
	defer srv.Close()

	con, err := redis.DialURL(fmt.Sprintf("redis://%s", srv.Addr()))
	if err != nil {
		panic(err)
	}
	defer con.Close()

	_, err = scpt.Do(con, "127.0.0.1", 1, 1)
	if err != nil {
		panic(err)
	}
	// TTL is one second so sleep and wait for it to expire
	time.Sleep(time.Second)

	_, err = scpt.Do(con, "127.0.0.1", 1, 1)
	if err != nil {
		// this should not happen because the key should have expired
		panic(err)
	}
}
```

**Comment by alicebob** [comment]
Thanks for your report.

Miniredis is frozen in time and won't expire anything by itself. You'll have to call `m.FastForward(some duration)` to have it expire keys.

`FastForward()` is mentioned in the readme, but it was pretty hidden. I made it a separate section, maybe that helps.

**Comment by alicebob** [comment]
And if you use `FastForward()` you can remove the `time.Sleep()` call, which is why it works this way.

**Comment by blockloop** [comment]
Arg! Sorry about that. I completely missed it. Thanks very much!

**Comment by alicebob** [comment]
No problem, good luck with the ratelimiter :)
