### ISSUE TITLE
[feature] support streams

### ISSUE THREAD

**Issue by dkrieger** [alicebob/miniredis#57]
Redis streams have been available in 5.0 release candidates for some time (**correction:** 5.0.0 has officially been released). antirez recently greatly expanded [documentation on streams](https://redis.io/commands/xack). github.com/go-redis/redis has full stream command support.

TL;DR: streams are upon us

Can stream support be added to the roadmap?

**Comment by alicebob** [comment]
I see no fundamental problem adding them, but it's quite a big topic.

How do you currently use them? Since implementing a basic version (maybe only XADD, XLEN, XRANGE?) is a lot more feasible.

**Comment by kathan24** [comment]
This is an amazing library to use and perform testing. 
I am looking for a XREAD functionality. I am using like 
`XREAD BLOCK 0 STREAMS mystream $` and `XREAD BLOCK 0 STREAMS mystream ID`

Any idea if XREAD could be implemented? If yes, when do you think it would land by?

**Comment by NefixEstrada** [comment]
What is the status of this issue? It seems that since 2.13.3 `XREAD` is supported, but it doesn't seem to work

**Comment by Lwing** [comment]
> First of all, this is an amazing library to use and perform testing. Thank you so much
> 
> I am looking for a XREAD functionality. I am using like
> `XREAD BLOCK 0 STREAMS mystream $` and `XREAD BLOCK 0 STREAMS mystream ID`
> 
> Any idea if XREAD could be implemented? If yes, when do you think it would land by?

basic implementation works
I've been looking into blocking calls a bit.
It seems to me that the whole application design is aimed towards single execution, i.e there doesn't seem to be an easy fix to handle multiple commands at the same time from the same client (which is a requirement for blocking calls).
I've implemented a basic (and naïve) handling of blocking xread, but the mutex blocks concurrent calls.. maybe there is a way to fix this..

**Comment by alicebob** [comment]
I just added a PR for `XREAD BLOCK`: #209. Branch is `xblock`.

**Comment by alicebob** [comment]
I've also added `block` and `noack` support to `xreadgroup` (#210). It's merged in master. I think that should be it for streams! (except some xinfo subcommands. Let me know if anyone cares about those)
