### ISSUE TITLE
How to mock sentinel or cluster?

### ISSUE THREAD

**Issue by axiaoxin** [alicebob/miniredis#58]

**Comment by alicebob** [comment]
There is no direct support for either.

Would you have any ideas what kind of support you would like to see?

**Comment by Jim-Lambert-Bose** [comment]
Here's the docs for implementing sentinel client: https://redis.io/topics/sentinel-clients

There are only a handful of commands needed.

**Comment by Jim-Lambert-Bose** [comment]
Would you be open to a PR that implements the following commands:
PING This command simply returns PONG.
SENTINEL masters Show a list of monitored masters and their state.
SENTINEL master <master name> Show the state and info of the specified master.
SENTINEL slaves <master name> Show a list of slaves for this master, and their state.
SENTINEL sentinels <master name> Show a list of sentinel instances for this master, and their state

**Comment by alicebob** [comment]
> Would you be open to a PR that implements the following commands:
> PING This command simply returns PONG.
> SENTINEL masters Show a list of monitored masters and their state.
> SENTINEL master <master name> Show the state and info of the specified master.
> SENTINEL slaves <master name> Show a list of slaves for this master, and their state.
> SENTINEL sentinels <master name> Show a list of sentinel instances for this master, and their state

With some sommands to add masters/slaves and their state? That would work.
Could you maybe first suggest the API in miniredis?

**Comment by Jim-Lambert-Bose** [comment]
> Would you be open to a PR that implements the following commands:
> SENTINEL masters Show a list of monitored masters and their state.
> SENTINEL master Show the state and info of the specified master.
> SENTINEL slaves Show a list of slaves for this master, and their state.
> SENTINEL sentinels Show a list of sentinel instances for this master, and their state

I'm not sure we need commands to add slaves and/or their state.  miniredis is a single process so it will always be the one and only master... and it will also be the one and only slave.  We just need it to listen on an additional port (26739) and respond to the commands above. Most of the state can be fairly static based on config.  Does that make sense?

**Comment by alicebob** [comment]
> > Would you be open to a PR that implements the following commands:
> > SENTINEL masters Show a list of monitored masters and their state.
> > SENTINEL master Show the state and info of the specified master.
> > SENTINEL slaves Show a list of slaves for this master, and their state.
> > SENTINEL sentinels Show a list of sentinel instances for this master, and their state
> 
> I'm not sure we need commands to add slaves and/or their state.  miniredis is a single process so it will always be the one and only master... and it will also be the one and only slave.  We just need it to listen on an additional port (26739) and respond to the commands above. Most of the state can be fairly static based on config.  Does that make sense?  

Yeah, but you still need some config. So you need some method(s) to set the
state. Or, as you said, we can also always have just the single master, but
that might be a bit too simple.

Just out of curiousity, are you testing something related to multiple redisses?

**Comment by Jim-Lambert-Bose** [comment]
I don't really need multiple redisses (or is that reddi).  I just need something to respond to sentinel requests.  

My use-case: during my multi-stage docker build (for a Go binary), I run integration tests that rely on sentinel giving me the master addr.  Currently, Dockerfile installs redis and sentinel, then has this mess in it:
`RUN (./redis-run.sh > redis.out & ) && (sleep 5) && (./sentinel-run.sh > sentinel.out &) && cd /my-service && go test -v -mod=vendor --timeout 240s -covermode=count -coverprofile=count.out`
This is hardly ideal.  BTW, my program doesn't care if the redis master and redis slave are the same addr.  If miniredis would respond to this minimal set of commands, I could use it for my integration tests in Docker.

**Comment by Jim-Lambert-Bose** [comment]
Yes, that would work great.

**Comment by Jim-Lambert-Bose** [comment]
I agree, a separate small package makes a lot of sense to me as well.

**Comment by Jim-Lambert-Bose** [comment]
Happy to do the work if you'd like a hand.

**Comment by alicebob** [comment]
> Happy to do the work if you'd like a hand.

Up to you :)
I don't mind working on it when I have some time, or if you beat me to it also
good.

**Comment by Jim-Lambert-Bose** [comment]
I'll try to bang something out tonight.

**Comment by Jim-Lambert-Bose** [comment]
It's a start: https://github.com/alicebob/miniredis/pull/74
I'm just looking for some feedback on where I'm headed... if you hate it just let me know and I'll try to accommodate your concerns.

**Comment by Jim-Lambert-Bose** [comment]
Good afternoon.  I've open sourced: https://github.com/Bose/minisentinel
it would be great if you could link to it.

**Comment by Jim-Lambert-Bose** [comment]
@alicebob good evening.  Just checking in to see if you saw my comment with:  https://github.com/Bose/minisentinel

**Comment by alicebob** [comment]
> @alicebob good evening.  Just checking in to see if you saw my comment with:  https://github.com/Bose/minisentinel

Hi,
thanks, yes I did, simply haven't gotten around to having a good yet, sorry. I will, though! :)

**Comment by Jim-Lambert-Bose** [comment]
ty.

**Comment by alicebob** [comment]
Looks good, thanks! I've put a link in the readme.
