### ISSUE TITLE
Is there any support for the redis pipelining ?

### ISSUE THREAD

**Issue by otaviojacobi** [alicebob/miniredis#60]
Hi all,
I'm currently trying to write unit tests for my redis integration module which does something like
```go
pipe := redisConn.Pipeline()
pipe.IncrBy(val1, val2)
pipe.Get(val3)
results, err := pipe.Exec()
```
Would it be possible to mock this pipelining with miniredis ? The Pipeline() I'm using is [this one](https://godoc.org/github.com/go-redis/redis#Client.Pipeline)

**Comment by alicebob** [comment]
I don't see why it wouldn't work. Did you try?

**Comment by otaviojacobi** [comment]
Yes, but I could not mock the pipeline/exec methods. I think I'll just mock the return from it and test. 
Thanks

**Comment by alicebob** [comment]
The pipeline seems only a client side optimization (to minimize network packets), and so I don't see how it shouldn't work as-is. Hmmm, weird.

**Comment by alicebob** [comment]
Aha, I get a runtime panic. Thanks for reporting :)

**Comment by alicebob** [comment]
this is what I used:

```
package main

import (
    "fmt"

    "github.com/alicebob/miniredis"
    "github.com/go-redis/redis"
)

func main() {
    s := miniredis.NewMiniRedis()
    c := redis.NewClient(&redis.Options{Addr: s.Addr()})

    pipe := c.Pipeline()
    pipe.IncrBy("foo", 42)
    pipe.Get("foo")
    results, err := pipe.Exec()
    fmt.Printf("%v %s\n", results, err)
}
```

**Comment by otaviojacobi** [comment]
Oh, nice ! I actually didn't run into the runtime panic, but I could use what you pointed out !
Many thanks !
