### ISSUE TITLE
adding support for GEOADD

### ISSUE THREAD

**Issue by Marlinski** [alicebob/miniredis#79]
Hi,

I have a project that requires GEOADD operation as well as GEOPOS and GEORADIUS. Do you plan to implements those commands for miniredis ? I saw that it was in the "probably not going to be implemented" but I was asking just to be sure :-)

**Comment by alicebob** [comment]
Hi @Marlinski,
thanks for your question.

I myself have no concrete plans to add it, but if anyone else also needs it please do comment here.

The GEO command you mention do not seem too complicated to add, especially since they re-use sorted sets. PRs are obviously always welcome :)

**Comment by sklinkert** [comment]
PR #82 is already pending.

**Comment by alicebob** [comment]
sorry for the long delay, GEO stuff turned out to be a bit of work :(

Just release v2.10.0, which has GEOADD, GEOPOS, and GEORADIUS. Thanks to @sklinkert !
