### ISSUE TITLE
Use an internal random number source rather than math/rand directly

### ISSUE THREAD

**Issue by zikaeroh** [alicebob/miniredis#83]
Commands like `SPOP` use `rand.Intn` directly, with the advised method of controlling the selection being to call `rand.Seed`. This means that any tests using miniredis which could normally be run in parallel cannot, as the `rand` package's seed is global and shared within the process.

Could a function be added to provide a seed, which could then be used internally to create a new `rand.Rand`? For backwards compatibility, it could default to the global functions in `rand`, but switch if a seed was provided. Something like:

```go
func (m *Miniredis) Seed(seed int) {
    // ...
}
```

Note that `rand.NewSource` (needed to call `rand.New`) does not return a goroutine-safe `Source`; it needs to have locking to ensure `Rand`'s accesses don't break things. (The stdlib has an unexported type for this.)

**Comment by alicebob** [comment]
> Commands like `SPOP` use `rand.Intn` directly, with the advised method of controlling the selection being to call `rand.Seed`. This means that any tests using miniredis which could normally be run in parallel cannot, as the `rand` package's seed is global and shared within the process.

Sounds like a good idea to me. I'll see if I can get around to it.

**Comment by alicebob** [comment]
Hi @zikaeroh,

I've implemented it in #87. I choose to do this in NewMiniRedis():

```
    source := rand.NewSource(rand.Int63())
    m := Miniredis{
        ....
        rand:        rand.New(source),
    }
```

This way seeding the global source still has some effect in Miniredis, while it give the option to override the seed. It's not 100% the same as before, but it's the simplest thing to do.

**Comment by zikaeroh** [comment]
I'll be happy to look at it more closely later. My first impression (skimming on my phone) that it'd definitely lead to different results between miniredis versions (since you're using a seed from Rand), and might also require some locking, but I haven't tested to see. I had actually been planning on submitting my own PR for consideration (but hadn't had time since asking).

**Comment by zikaeroh** [comment]
I opened a slightly different PR (#89) for your consideration; this one instead calls the global rand as it would have before, but will switch to an internal version when requested. I think this is better than always using an internal copy with `rand.Int63()` as a seed because:

- Using `rand.Int63()` changes the seed used (as it wouldn't output `1`, Go's default seed), so those who had used the old advice of `rand.Seed` would have broke those users.
- The library would still rely on global state; every miniredis instance created would call `rand.Int63()` and would all behave differently (in case a test creates more than one server, only has one of them use randomness, etc).

**Comment by alicebob** [comment]
> I'll be happy to look at it more closely later. My first impression (skimming on my phone) that it'd definitely lead to different results between miniredis versions (since you're using a seed from Rand),

It will be different results, but they will still be random. :)

> and might also require some locking,

It should be fine, ever rand use is under the big mutex in *Miniredis thanks to
withTx().

>  but I haven't tested to see. I had actually been planning on submitting my own PR for consideration (but hadn't had time since asking).

OK! That would also be good. Feel free to start from mine, if that helps.

**Comment by zikaeroh** [comment]
Sure, random is random, except that existing users may have already taken the advice of using the global seed in non parallel tests, and would otherwise be broken. (The fact that we can seed at all is really because it's only psuedorandom anyway, which is intended.)
