### ISSUE TITLE
Possibly incorrect response when transactions are aborted

### ISSUE THREAD

**Issue by zeebo** [alicebob/miniredis#94]
The code for aborting transactions reports a length of `0` during an abort as follows:

https://github.com/alicebob/miniredis/blob/4eb0915dc3fb0b318cb25f67d9057e3b492d3283/cmd_transactions.go#L75-L82

The `redis-go/redis` library, however, checks for a `Null` response to recognize that the transaction was aborted (https://github.com/go-redis/redis/blob/6bc7daa5b1e86745a6976ac1c4dfe6c76ea6af1f/redis.go#L425-L442)

```go
	// Parse number of replies.
	line, err := rd.ReadLine()
	if err != nil {
		if err == Nil {
			err = TxFailedErr
		}
		return err
	}

	switch line[0] {
	case proto.ErrorReply:
		return proto.ParseErrorReply(line)
	case proto.ArrayReply:
		// ok
	default:
		err := fmt.Errorf("redis: expected '*', but got line %q", line)
		return err
	}
```

(Indeed, it will attempt to read a response for every command regardless of the returned length. This causes a read timeout which is how I wound up finding all this. Perhaps that's an issue for that library as well.)

The redis documentation for the `EXEC` command (https://redis.io/commands/exec) claims

> When using WATCH, EXEC can return a Null reply if the execution was aborted.

which leads me to believe that `Null` is the appropriate response here, and in my testing, redis itself does report a `Null`. Should the server be changed to report a `Null` instead of `0`?

I wanted to open an issue for discussion because from what I can tell, the current response has been the same from it's initial introduction ~4-5 years ago.

**Comment by alicebob** [comment]
> I wanted to open an issue for discussion because from what I can tell, the current response has been the same from it's initial introduction ~4-5 years ago.

Hi,

thanks for the issue! Sounds like you're right, and we should change it. If you
feel like making a PR, please do, otherwise I'll get to it in a few days.
