### ISSUE TITLE
Incorrect behavior for ZRANGEBYLEX

### ISSUE THREAD

**Issue by shazow** [alicebob/miniredis#99]
Hi there, I ran into a scenario where ZRANGEBYLEX seems to handle the Min field incorrectly, at least that's what I suspect.

I have reproduced it using `github.com/alicebob/miniredis/v2 v2.9.1-0.20190731113429-5da194369a10`, with both redigo and go-redis.

The test cases are here: https://gist.github.com/shazow/2c9355d31d41cc0e654d374aed0e69bc

To summarize, this scenario returns "ccc" incorrectly for the second command:

```
redis> ZADD idx 0 "ccc"
(integer) 1
redis> ZRANGEBYLEX idx "[d" "[e"
(empty list or set)
redis> ZRANGEBYLEX idx "[c" "[d"
1) "ccc"
```

**Comment by alicebob** [comment]
> Hi there, I ran into a scenario where ZRANGEBYLEX seems to handle the Min field incorrectly, at least that's what I suspect.

Thanks for the report! I'll have a look soon.

**Comment by shazow** [comment]
Reading through the code, looks like the `(` and `[` exclusive/inclusive prefixes aren't special-treated, so I guess it's taking [ an alphanumeric prefix:

https://github.com/alicebob/miniredis/blob/master/cmd_sorted_set.go#L1123

**Comment by shazow** [comment]
Ah found the problem, if there's a zero set result, it never overrides members. I'll send a PR!
